import { currentStateLessons } from "@/content/current-state-module";
import { dataIntegrationLessons } from "@/content/data-integration-module";
import { discoveryLessons } from "@/content/discovery-module";
import { applicationDimensionDesignLessons } from "@/content/application-dimension-design-module";
import { futureStateLessons } from "@/content/future-state-module";
import { metadataBuildLessons } from "@/content/metadata-build-module";
import { requirementTraceabilityLessons } from "@/content/requirement-traceability-module";
import { solutionArchitectureLessons } from "@/content/solution-architecture-module";
import { salesPlanningLessons } from "@/content/sales-planning-build-module";
import { productionPlanningLessons } from "@/content/production-planning-build-module";
import { inventoryPlanningLessons } from "@/content/inventory-planning-module";
import { manufacturingCostLessons } from "@/content/manufacturing-cost-cogs-module";
import { workforceCapexLessons } from "@/content/workforce-capex-dependencies-module";
import { financialStatementLessons } from "@/content/financial-statement-integration-module";
import { businessRulesGroovyLessons } from "@/content/business-rules-groovy-module";
import { formsDashboardsSmartViewLessons } from "@/content/forms-dashboards-smart-view-module";
import { securityWorkflowLessons } from "@/content/security-workflow-module";
import { scenarioWhatIfLessons } from "@/content/scenario-what-if-planning-module";
import { systemIntegrationTestingLessons } from "@/content/system-integration-testing-module";
import { performanceTestingLessons } from "@/content/performance-testing-module";
import { userAcceptanceTestingLessons } from "@/content/user-acceptance-testing-module";
import { defectManagementLessons } from "@/content/defect-management-module";
import { cutoverLessons } from "@/content/cutover-module";
import { goNoGoLessons } from "@/content/go-no-go-module";
import { goLiveLessons } from "@/content/go-live-module";
import { hypercareLessons } from "@/content/hypercare-module";
import { bauLessons } from "@/content/bau-continuous-improvement-module";
import { monthlyPlanningCapstoneLessons } from "@/content/monthly-planning-capstone";
import { productionSalesPlanningCourse } from "@/content/production-sales-planning";
import type { CourseModuleDefinition, LearningTrackId } from "@/types/course";

const implementedModules: CourseModuleDefinition[] = [
  {
    id: "implementation-discovery",
    slug: "discovery",
    trackId: "implementation",
    sequence: 1,
    phase: 1,
    title: "Discovery & Requirement Gathering",
    stage: "Discover · Foundation",
    description: "Understand the business, interview stakeholders, examine evidence, write testable requirements, and complete an applied Discovery pack.",
    duration: "144 min",
    deliverable: "Approved discovery pack and requirement catalogue",
    exitGate: "Guided work, applied homework, objectives, scope, stakeholders, evidence, requirements, open items, and sign-off are complete",
    status: "available",
    lessons: discoveryLessons,
  },
  {
    id: "implementation-current-state",
    slug: "current-state",
    trackId: "implementation",
    sequence: 2,
    phase: 2,
    title: "Current-State Assessment",
    stage: "Discover · Assessment",
    description: "Validate real planning processes, handoffs, systems, data, controls, root causes, and measurable AS-IS performance through evidence.",
    duration: "148 min",
    deliverable: "Agreed current-state assessment pack and measurable AS-IS baseline",
    exitGate: "Guided work, applied homework, process and interface evidence, root causes, baselines, open items, knowledge check, and business agreement are complete",
    status: "available",
    prerequisiteModuleId: "implementation-discovery",
    lessons: currentStateLessons,
  },
  {
    id: "implementation-future-state",
    slug: "future-state",
    trackId: "implementation",
    sequence: 3,
    phase: 3,
    title: "Future-State Design",
    stage: "Design · Blueprint",
    description: "Convert validated findings into a connected target operating model covering outcomes, ownership, decision grains, calendar, governance, exceptions, controls, and measures.",
    duration: "154 min",
    deliverable: "Approved future-state design package and stakeholder agreement",
    exitGate: "Guided work, applied homework, process, ownership, grain, calendar, exceptions, controls, KPIs, open items, knowledge check, and stakeholder agreement are complete",
    status: "available",
    prerequisiteModuleId: "implementation-current-state",
    lessons: futureStateLessons,
  },
  {
    id: "implementation-requirement-traceability",
    slug: "requirement-traceability",
    trackId: "implementation",
    sequence: 4,
    phase: 4,
    title: "Requirement Traceability",
    stage: "Design · Governance",
    description: "Build and govern the RTM from approved outcomes through requirement quality, ownership, release scope, design/build mappings, verification evidence, coverage, and controlled change.",
    duration: "154 min",
    deliverable: "Approved, versioned, and coverage-reviewed RTM baseline",
    exitGate: "Guided work, applied homework, requirement quality, ownership, release assignment, lifecycle mapping, evidence coverage, gap control, change history, knowledge check, and sign-off are complete",
    status: "available",
    prerequisiteModuleId: "implementation-future-state",
    lessons: requirementTraceabilityLessons,
  },
  {
    id: "implementation-solution-architecture",
    slug: "solution-architecture",
    trackId: "implementation",
    sequence: 5,
    phase: 5,
    title: "Solution Architecture",
    stage: "Design · Architecture",
    description: "Define system boundaries, connected planning capabilities, user experiences, integrations, environments, security, measurable non-functional requirements, recovery, and support controls.",
    duration: "160 min",
    deliverable: "Approved solution architecture baseline and decision package",
    exitGate: "Boundaries, decisions, trade-offs, flows, controls, dependencies, risks, owners, and approvals are recorded and ready for detailed application design",
    status: "available",
    prerequisiteModuleId: "implementation-requirement-traceability",
    lessons: solutionArchitectureLessons,
  },
  {
    id: "implementation-application-dimension-design",
    slug: "application-dimension-design",
    trackId: "implementation",
    sequence: 6,
    phase: 6,
    title: "Application & Dimension Design",
    stage: "Design · Detailed design",
    description: "Define and review the Oracle application setup, dimensions, planning grains, hierarchies, member properties, cubes, valid intersections, data movement, and performance assumptions.",
    duration: "170 min",
    deliverable: "Approved application and dimension design baseline with screenshot-guided runbook",
    exitGate: "Setup decisions, grains, dimensions, properties, cube participation, intersections, controls, evidence, risks, owners, and approvals are ready for metadata build",
    status: "available",
    prerequisiteModuleId: "implementation-solution-architecture",
    lessons: applicationDimensionDesignLessons,
  },
  {
    id: "implementation-metadata-build",
    slug: "metadata-build",
    trackId: "implementation",
    sequence: 7,
    phase: 7,
    title: "Metadata Build",
    stage: "Build · Metadata configuration",
    description: "Prepare tenant-derived files, create and import governed metadata, diagnose rejects, refresh safely, reconcile results, and baseline the built structures.",
    duration: "225 min",
    deliverable: "Reconciled metadata baseline with import, refresh, smoke-test, and post-build export evidence",
    exitGate: "Approved metadata is loaded, refreshed where required, reconciled to control totals, independently reviewed, and ready for forms and calculation configuration",
    status: "available",
    prerequisiteModuleId: "implementation-application-dimension-design",
    lessons: metadataBuildLessons,
  },
  {
    id: "implementation-data-integration",
    slug: "data-integration",
    trackId: "implementation",
    sequence: 8,
    phase: 8,
    title: "Data Integration",
    stage: "Build · Data integration",
    description: "Define source contracts, configure a file-based integration, map dimensions and members, stage and validate data, export safely, resolve rejects, and reconcile Planning totals.",
    duration: "241 min",
    deliverable: "Reconciled file-based integration baseline, runbook, mappings, Process Details, and source-to-Planning evidence",
    exitGate: "The controlled load is repeatable, mappings and runtime options are reviewed, rejects are resolved, source and Planning totals reconcile, and automation prerequisites are owned",
    status: "available",
    prerequisiteModuleId: "implementation-metadata-build",
    lessons: dataIntegrationLessons,
  },
  {
    id: "implementation-sales-planning-build",
    slug: "sales-planning-build",
    trackId: "implementation",
    sequence: 9,
    phase: 9,
    title: "Sales Planning Build",
    stage: "Build · Sales planning model",
    description: "Build and prove the controlled path from reconciled history through baseline, promotion, overrides, consensus demand, net price, revenue, exceptions, and downstream handoff.",
    duration: "269 min",
    deliverable: "Reconciled sales-planning model, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Consensus units and net revenue reconcile from approved inputs through calculations, controls, forms, exceptions, evidence, and downstream handoff",
    status: "available",
    prerequisiteModuleId: "implementation-data-integration",
    lessons: salesPlanningLessons,
  },
  {
    id: "implementation-production-planning-build",
    slug: "production-planning-build",
    trackId: "implementation",
    sequence: 10,
    phase: 10,
    title: "Production Planning Build",
    stage: "Build · Production planning model",
    description: "Translate approved demand into yield-adjusted production requirements, plant allocations, capacity utilization, governed exceptions, and a reconciled manufacturing handoff.",
    duration: "268 min",
    deliverable: "Reconciled production-planning model, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Demand, inventory bridge, yield, lots, plant allocations, capacity, exceptions, scoped execution, reconciliation, and the Phase 11 rerun trigger are approved",
    status: "available",
    prerequisiteModuleId: "implementation-sales-planning-build",
    lessons: productionPlanningLessons,
  },
  {
    id: "implementation-inventory-planning",
    slug: "inventory-planning",
    trackId: "implementation",
    sequence: 11,
    phase: 11,
    title: "Inventory Planning",
    stage: "Build · Inventory planning model",
    description: "Convert governed stock and differentiated service policy into target inventory, projected cover, plant deployment, controlled production reruns, and a reconciled downstream handoff.",
    duration: "270 min",
    deliverable: "Approved inventory-planning model, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Opening inventory, policy, targets, projections, plant deployment, exceptions, Phase 10 reruns, forms, jobs, reconciliations, and downstream handoff are approved",
    status: "available",
    prerequisiteModuleId: "implementation-production-planning-build",
    lessons: inventoryPlanningLessons,
  },
  {
    id: "implementation-manufacturing-cost-cogs",
    slug: "manufacturing-cost-cogs",
    trackId: "implementation",
    sequence: 12,
    phase: 12,
    title: "Manufacturing Cost & COGS",
    stage: "Build · Manufacturing cost and COGS",
    description: "Build governed material, labor, and overhead standards; value production and inventory; calculate COGS and gross margin; and reconcile Plan1 detail to reporting.",
    duration: "278 min",
    deliverable: "Approved manufacturing-cost and COGS model, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Cost drivers, unit cost, production and inventory valuation, COGS, gross margin, exceptions, operational reruns, jobs, and reporting reconciliations are approved",
    status: "available",
    prerequisiteModuleId: "implementation-inventory-planning",
    lessons: manufacturingCostLessons,
  },
  {
    id: "implementation-workforce-capex-dependencies",
    slug: "workforce-capex-dependencies",
    trackId: "implementation",
    sequence: 13,
    phase: 13,
    title: "Workforce & CapEx Dependencies",
    stage: "Build · Workforce and CapEx dependencies",
    description: "Translate production requirements into workforce capacity, governed staffing actions, asset-capacity decisions, CapEx timing, cash flow, depreciation, scenarios, and downstream financial impacts.",
    duration: "276 min",
    deliverable: "Approved workforce and CapEx dependency baseline, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Operational handoff, workforce drivers and actions, asset capacity, CapEx timing, cash, depreciation, scenarios, exceptions, reruns, jobs, and reporting reconciliations are approved",
    status: "available",
    prerequisiteModuleId: "implementation-manufacturing-cost-cogs",
    lessons: workforceCapexLessons,
  },
  {
    id: "implementation-financial-statement-integration",
    slug: "financial-statement-integration",
    trackId: "implementation",
    sequence: 14,
    phase: 14,
    title: "Financial Statement Integration",
    stage: "Build · Financial statement integration",
    description: "Connect approved revenue, COGS, inventory, workforce, CapEx, cash, debt, tax, and equity assumptions into a balanced management P&L, indirect cash flow, and balance sheet.",
    duration: "282 min",
    deliverable: "Approved integrated management statements, functional walkthrough, hands-on lab, and evidence package",
    exitGate: "Mappings, P&L, working capital, cash flow, balance sheet, source reruns, reporting movement, full-precision controls, limitations, jobs, and reconciliations are approved",
    status: "available",
    prerequisiteModuleId: "implementation-workforce-capex-dependencies",
    lessons: financialStatementLessons,
  },
  {
    id: "implementation-business-rules-groovy",
    slug: "business-rules-groovy",
    trackId: "implementation",
    sequence: 15,
    phase: 15,
    title: "Business Rules & Groovy",
    stage: "Build · Business rules and Groovy",
    description: "Engineer governed Calculation Manager and Groovy rules with bounded prompts, grid-aware execution, dependency controls, deployment evidence, and repeatable results.",
    duration: "289 min",
    deliverable: "Approved rule catalogue, source artifacts, functional walkthrough, applied engineering lab, deployment package, test evidence, and operating runbook",
    exitGate: "Rule selection, specifications, prompts, calculation scope, Groovy guardrails, rulesets, deployment, launch access, jobs, repeatability, performance, reconciliation, recovery, and approvals are complete",
    status: "available",
    prerequisiteModuleId: "implementation-financial-statement-integration",
    lessons: businessRulesGroovyLessons,
  },
  {
    id: "implementation-forms-dashboards-smart-view",
    slug: "forms-dashboards-smart-view",
    trackId: "implementation",
    sequence: 16,
    phase: 16,
    title: "Forms, Dashboards & Smart View",
    stage: "Build · Forms, dashboards, and Smart View",
    description: "Create role-based Plan1 forms, reconciled ApexPlan ASO dashboards, and controlled Smart View workflows with clear context, validation, actions, and evidence.",
    duration: "294 min",
    deliverable: "Approved role journeys, form and KPI catalogues, configured workspace, Smart View package, functional walkthrough, applied lab, test evidence, and operating guide",
    exitGate: "Navigation, forms, POVs, cell behavior, validations, rule actions, dashboards, Smart View, access behavior, usability, accessibility, performance, reconciliation, support, and approvals are complete",
    status: "available",
    prerequisiteModuleId: "implementation-business-rules-groovy",
    lessons: formsDashboardsSmartViewLessons,
  },
  {
    id: "implementation-security-workflow",
    slug: "security-workflow",
    trackId: "implementation",
    sequence: 17,
    phase: 17,
    title: "Security & Workflow",
    stage: "Build · Security and workflow",
    description: "Implement least-privilege access across roles, groups, data, artifacts, rules, and Smart View, then govern ownership and evidence through Planning Approvals and Task Manager.",
    duration: "294 min",
    deliverable: "Approved security baseline, approval-unit workflow, Task Manager schedule, functional walkthrough, applied lab, test evidence, and operating guide",
    exitGate: "Roles, groups, data and artifact access, rule launch rights, Planning Approvals, Task Manager, segregation, positive and negative tests, reconciliations, exceptions, support, and approvals are complete",
    status: "available",
    prerequisiteModuleId: "implementation-forms-dashboards-smart-view",
    lessons: securityWorkflowLessons,
  },
  {
    id: "implementation-scenario-what-if-planning",
    slug: "scenario-what-if-planning",
    trackId: "implementation",
    sequence: 18,
    phase: 18,
    title: "Scenario & What-If Planning",
    stage: "Build · Scenario and what-if planning",
    description: "Create controlled Upside and Downside versions from the protected Forecast / Final baseline, trace driver effects through operations and finance, compare outcomes, and promote only an approved, reconciled case.",
    duration: "298 min",
    deliverable: "Approved Version design, protected baseline, governed alternatives, comparison package, functional walkthrough, applied lab, decision record, and operating guide",
    exitGate: "Version design, baseline, copies, drivers, calculations, dependencies, comparisons, sensitivities, exceptions, selected-case promotion, workflow, publish, reconciliation, security, support, and approvals are complete",
    status: "available",
    prerequisiteModuleId: "implementation-security-workflow",
    lessons: scenarioWhatIfLessons,
  },
  {
    id: "implementation-system-integration-testing",
    slug: "system-integration-testing",
    trackId: "implementation",
    sequence: 19,
    phase: 19,
    title: "System Integration Testing",
    stage: "Validate · System integration testing",
    description: "Prove the integrated ApexPlan solution from controlled source data through interfaces, Plan1 calculations, cross-module dependencies, security, workflow, Smart View, ApexPlan ASO reporting, failure recovery, and reconciliation.",
    duration: "308 min",
    deliverable: "Approved SIT strategy, coverage, data pack, end-to-end and recovery evidence, reconciliation package, defect results, applied lab, status report, and exit decision",
    exitGate: "Requirements and interfaces, data, integrations, calculations, modules, cubes, channels, security, workflow, failures, recovery, repeatability, defects, retests, regression, reconciliations, risks, waivers, and the authorized SIT decision are complete",
    status: "available",
    prerequisiteModuleId: "implementation-scenario-what-if-planning",
    lessons: systemIntegrationTestingLessons,
  },
  {
    id: "implementation-performance-testing",
    slug: "performance-testing",
    trackId: "implementation",
    sequence: 20,
    phase: 20,
    title: "Performance Testing",
    stage: "Validate · Performance testing",
    description: "Measure the frozen ApexPlan release under representative single-user and concurrent workloads, diagnose evidence-backed bottlenecks, optimize safely, reconcile correctness, and approve capacity and operational conditions.",
    duration: "330 min",
    deliverable: "Approved performance strategy, workload and target catalogue, baseline and load evidence, diagnostics, before-and-after optimization, capacity assessment, applied lab, and exit decision",
    exitGate: "Targets, workloads, environment, data volume, single-user and concurrent results, statistics, errors, diagnostics, optimization, functional reconciliation, stability, capacity, defects, limitations, monitoring, risks, waivers, and the authorized performance decision are complete",
    status: "available",
    prerequisiteModuleId: "implementation-system-integration-testing",
    lessons: performanceTestingLessons,
  },
  {
    id: "implementation-user-acceptance-testing",
    slug: "user-acceptance-testing",
    trackId: "implementation",
    sequence: 21,
    phase: 21,
    title: "User Acceptance Testing",
    stage: "Validate · User acceptance testing",
    description: "Enable representative Apex business users to execute realistic planning, review, approval, Smart View, and reporting journeys; govern issues and retests; and formally accept a defined release, scope, risk, and deployment condition.",
    duration: "302 min",
    deliverable: "Approved UAT charter, business journeys, user and data pack, executed scripts, issue and retest evidence, reconciliations, status report, applied lab, and formal business acceptance",
    exitGate: "Business journey and role coverage, scripts, actual results, workflow and reporting evidence, issues, fixes, retest, regression, reconciliations, training, support, open risks, deployment conditions, and authorized acceptance are complete",
    status: "available",
    prerequisiteModuleId: "implementation-performance-testing",
    lessons: userAcceptanceTestingLessons,
  },
  {
    id: "implementation-defect-management",
    slug: "defect-management",
    trackId: "implementation",
    sequence: 22,
    phase: 22,
    title: "Defect Management",
    stage: "Validate · Defect management",
    description: "Govern every ApexPlan issue from evidence-backed classification and triage through controlled fix, retest, regression, reconciliation, deferral, closure, and release authorization.",
    duration: "287 min",
    deliverable: "Approved defect plan, authoritative register, triage and ageing evidence, fix-build traceability, retest and regression results, reconciliations, controlled deferrals, release-readiness readout, applied lab, and closure decision",
    exitGate: "The release and register snapshot, classification, impact, ownership, SLA, ageing, fixes, controlled promotion, retest, regression, reconciliations, duplicates, changes, deferrals, residual risks, approvals, and cutover recommendation are complete",
    status: "available",
    prerequisiteModuleId: "implementation-user-acceptance-testing",
    lessons: defectManagementLessons,
  },
  {
    id: "implementation-cutover",
    slug: "cutover",
    trackId: "implementation",
    sequence: 23,
    phase: 23,
    title: "Cutover",
    stage: "Deploy · Cutover",
    description: "Move the approved ApexPlan release into production through a dependency-driven runbook covering configuration, final data, validation, recovery, evidence, communications, and decision authority.",
    duration: "300 min",
    deliverable: "Approved cutover strategy and runbook, release and migration evidence, final loads and reconciliations, rehearsal timings, rollback and communication plans, command-center log, applied lab, and Go/No-Go evidence pack",
    exitGate: "Entry criteria, scope, freeze, package versions, snapshots, migrations, environment settings, source files, loads, rejects, calculations, publishing, reconciliations, security, workflow, integrations, schedules, smoke tests, rehearsal timing, deviations, rollback readiness, communications, support handoff, risks, and recommendation are complete",
    status: "available",
    prerequisiteModuleId: "implementation-defect-management",
    lessons: cutoverLessons,
  },
  {
    id: "implementation-go-no-go",
    slug: "go-no-go",
    trackId: "implementation",
    sequence: 24,
    phase: 24,
    title: "Go / No-Go",
    stage: "Deploy · Decision gate",
    description: "Convert the completed ApexPlan cutover evidence into an authorized Go, Go with conditions, or No-Go decision using predefined hard stops, residual-risk controls, and a signed operational handoff.",
    duration: "262 min",
    deliverable: "Approved gate catalogue and register, residual-risk and condition records, decision-board evidence, signed decision record, stakeholder communication, applied lab, and Go-Live or remediation handoff",
    exitGate: "The exact release, evidence snapshot, hard-stop results, conditions, cumulative residual risk, recovery state, authority, quorum, rationale, dissent, decision time, activation scope, communication, owners, and first checkpoint are complete and signed",
    status: "available",
    prerequisiteModuleId: "implementation-cutover",
    lessons: goNoGoLessons,
  },
  {
    id: "implementation-go-live",
    slug: "go-live",
    trackId: "implementation",
    sequence: 25,
    phase: 25,
    title: "Go-Live",
    stage: "Deploy · Production activation",
    description: "Activate the authorized ApexPlan production scope in controlled user and automation waves, prove the first live planning cycle, reconcile every output channel, contain incidents, and transfer a known state to Hypercare.",
    duration: "282 min",
    deliverable: "Approved activation runbook, production access and automation evidence, first-cycle execution and reconciliations, screenshot-guided walkthrough, incident record, applied lab, production validation pack, and accepted Hypercare handoff",
    exitGate: "Production identity, authorized scope, user and automation waves, first-cycle forms, rules, workflow, reporting, full-precision reconciliation, security, performance, incidents, conditions, recovery, monitoring, communication, support ownership, and Hypercare acceptance are complete",
    status: "available",
    prerequisiteModuleId: "implementation-go-no-go",
    lessons: goLiveLessons,
  },
  {
    id: "implementation-hypercare",
    slug: "hypercare",
    trackId: "implementation",
    sequence: 26,
    phase: 26,
    title: "Hypercare",
    stage: "Operate · Production stabilization",
    description: "Stabilize ApexPlan through an evidence-led command center, correct support classification, layered monitoring, controlled fixes, recurring-cause removal, knowledge transfer, and measurable BAU acceptance.",
    duration: "274 min",
    deliverable: "Approved command-center record, incident and problem traceability, monitoring controls, fix and regression evidence, support knowledge, applied lab, closure pack, and accepted BAU handoff",
    exitGate: "The agreed stability window, service-health thresholds, reconciliations, performance, incident and recurrence trends, conditions, changes, known errors, support capability, residual risks, BAU owners, closure communication, and signed exit decision are complete",
    status: "available",
    prerequisiteModuleId: "implementation-go-live",
    lessons: hypercareLessons,
  },
  {
    id: "implementation-bau-continuous-improvement",
    slug: "bau-continuous-improvement",
    trackId: "implementation",
    sequence: 27,
    phase: 27,
    title: "BAU & Continuous Improvement",
    stage: "Operate · Service and product improvement",
    description: "Operate ApexPlan through an accountable service model, integrated planning and release calendars, complete service-health controls, governed improvement intake, regression protection, durable knowledge, adoption, and measurable value realization.",
    duration: "288 min",
    deliverable: "Approved BAU service charter and calendar, service-health scorecard, governed improvement backlog, release and regression model, operational knowledge, adoption and benefits register, applied lab, funded roadmap, and program-completion record",
    exitGate: "Service and product ownership, decision rights, operating calendar, controls, scorecard, support, recovery, backlog decisions, release governance, regression, knowledge, adoption, benefits, residual risks, funding, roadmap, and business and technology acceptance are complete",
    status: "available",
    prerequisiteModuleId: "implementation-hypercare",
    lessons: bauLessons,
  },
];

const implementationPlaceholders: CourseModuleDefinition[] = productionSalesPlanningCourse.phases
  .filter((phase) => phase.id > 27)
  .map((phase) => ({
    id: `implementation-${phase.id}`,
    slug: `phase-${phase.id}`,
    trackId: "implementation",
    sequence: phase.id,
    phase: phase.id,
    title: phase.title,
    stage: phase.stage.charAt(0).toUpperCase() + phase.stage.slice(1),
    description: "Content will be added after the preceding lifecycle deliverable is validated.",
    duration: "Planned",
    deliverable: "Defined during detailed module design",
    exitGate: "Defined during detailed module design",
    status: "planned",
    prerequisiteModuleId: `implementation-${phase.id - 1}`,
    lessons: [],
  }));

export const planningCycleModules: CourseModuleDefinition[] = [
  {
    id: "planning-cycle-capstone",
    slug: "monthly-planning-capstone",
    trackId: "planning-cycle",
    sequence: 1,
    title: "End-to-End Monthly Planning Capstone",
    stage: "Operate · Workshop capstone",
    description: "Operate the implemented ApexPlan solution from actuals readiness through demand, supply, finance, scenario approval, publication, reconciliation, and cycle close.",
    duration: "174 min",
    deliverable: "Approved monthly planning evidence pack and executive cycle readout",
    exitGate: "The approved operational and financial plan is published, reconciled, owned, and defensible from source controls through the next-cycle actions",
    status: "available",
    lessons: monthlyPlanningCapstoneLessons,
  },
];

export const implementationModules = [...implementedModules, ...implementationPlaceholders];

export function getModulesForTrack(trackId: LearningTrackId) {
  return trackId === "implementation" ? implementationModules : planningCycleModules;
}

export function getModuleById(moduleId: string) {
  return [...implementationModules, ...planningCycleModules].find((module) => module.id === moduleId);
}

export function getModuleBySlug(moduleSlug: string) {
  return [...implementationModules, ...planningCycleModules].find((module) => module.slug === moduleSlug);
}
