export const formsDashboardsSmartViewLessons = [
  { id: "ux-foundations", number: "01", title: "User-experience strategy and role journeys", duration: "18 min", type: "concept" },
  { id: "form-design-contract", number: "02", title: "Design the form catalogue, POV, and layout", duration: "28 min", type: "assessment" },
  { id: "planning-input-forms", number: "03", title: "Build focused planning input and review forms", duration: "32 min", type: "simulation" },
  { id: "form-rules-validation", number: "04", title: "Integrate validation, actions, and business rules", duration: "28 min", type: "wizard" },
  { id: "decision-dashboards", number: "05", title: "Build decision-oriented dashboards", duration: "30 min", type: "simulation" },
  { id: "smart-view", number: "06", title: "Design the controlled Smart View experience", duration: "32 min", type: "assessment" },
  { id: "ux-performance-testing", number: "07", title: "Test usability, access, and performance", duration: "28 min", type: "assessment" },
  { id: "ux-walkthrough", number: "08", title: "Execute the forms, dashboards, and Smart View walkthrough", duration: "30 min", type: "guided-screenshot" },
  { id: "ux-homework", number: "09", title: "Applied planner workspace lab", duration: "44 min", type: "assessment" },
  { id: "ux-exit-gate", number: "10", title: "UX catalogue, evidence package, and exit gate", duration: "24 min", type: "exit-gate" },
] as const;

export type FormsDashboardsSmartViewLessonId = (typeof formsDashboardsSmartViewLessons)[number]["id"];

export const uxReadinessControls = [
  "Phase 15 rule names, runtime prompts, launch locations, expected results, job evidence, and failure messages are stable enough to integrate with user-facing artifacts",
  "Planner, reviewer, finance, operations, administrator, and executive journeys have named tasks, decisions, frequencies, devices, data scopes, and ownership",
  "Plan1 is the controlled input and detailed-calculation cube while ApexPlan ASO is the reconciled management-reporting destination",
  "Writable, calculated, sourced, protected, read-only, comment, attachment, Smart List, and supporting-detail behaviors are identified before form layout begins",
  "Forms and dashboards will simplify approved work; they will not hide unresolved process, metadata, rule, security, or performance problems",
] as const;

export const personaJourneyCases = [
  { id: "UJ-01", issue: "A sales planner sees workforce, CapEx, debt, tax, and administrative forms in the same navigation cluster.", correct: "Expose a role-based sales workspace containing only required input, review, exception, and submission tasks", options: ["Expose a role-based sales workspace containing only required input, review, exception, and submission tasks", "Show every artifact for transparency", "Move all planning to Smart View"] },
  { id: "UJ-02", issue: "An operations reviewer must move through demand, inventory, production, capacity, and exceptions in a controlled sequence.", correct: "Create a task-oriented navigation flow with clear status, handoffs, dependencies, and return paths", options: ["Create a task-oriented navigation flow with clear status, handoffs, dependencies, and return paths", "List forms alphabetically", "Use browser bookmarks as the process"] },
  { id: "UJ-03", issue: "Executives need an exception and decision view but are given a detailed writable input grid.", correct: "Use a read-only dashboard with governed KPIs, filters, thresholds, drill paths, and decision context", options: ["Use a read-only dashboard with governed KPIs, filters, thresholds, drill paths, and decision context", "Let executives edit calculated totals", "Email screenshots of every form"] },
  { id: "UJ-04", issue: "Finance needs controlled spreadsheet analysis without creating a shadow planning model.", correct: "Provide governed Smart View forms or ad hoc access with defined POV, writable scope, refresh-submit behavior, templates, and reconciliation", options: ["Provide governed Smart View forms or ad hoc access with defined POV, writable scope, refresh-submit behavior, templates, and reconciliation", "Allow disconnected workbooks to become the system of record", "Export values and remove the connection"] },
] as const;

export const formDesignCases = [
  { id: "FD-01", issue: "One form contains sales, production, inventory, workforce, CapEx, and statements across thousands of visible intersections.", correct: "Split the workspace into task-focused forms with a common POV and explicit handoffs", options: ["Split the workspace into task-focused forms with a common POV and explicit handoffs", "Add more frozen columns", "Hide random rows"] },
  { id: "FD-02", issue: "Scenario and Version appear on columns and users repeatedly submit to the wrong combination.", correct: "Place Scenario and Version in the page or POV, show them prominently, and use approved defaults and valid combinations", options: ["Place Scenario and Version in the page or POV, show them prominently, and use approved defaults and valid combinations", "Keep them on columns", "Remove Version from the display"] },
  { id: "FD-03", issue: "Input, calculated, sourced, and read-only cells look identical.", correct: "Use consistent formatting, labels, instructions, legends, precision, and protection so cell behavior is obvious", options: ["Use consistent formatting, labels, instructions, legends, precision, and protection so cell behavior is obvious", "Explain the difference only in training", "Make all cells writable"] },
  { id: "FD-04", issue: "Suppress Missing Blocks is enabled without comparing load time, row count, Dynamic Calc behavior, or Smart View impact.", correct: "Benchmark the representative form before and after suppression and retain the setting only when results and usability remain correct", options: ["Benchmark the representative form before and after suppression and retain the setting only when results and usability remain correct", "Always enable every suppression option", "Never suppress missing data"] },
] as const;

export const formBehaviorCases = [
  { id: "FB-01", issue: "A planner changes Pune production but the form accepts a value that is not a 20-unit lot multiple.", correct: "Validate the edited cell, explain the required lot size, block invalid submission, and preserve the previous approved value", options: ["Validate the edited cell, explain the required lot size, block invalid submission, and preserve the previous approved value", "Round silently after save", "Accept the value and fix it offline"] },
  { id: "FB-02", issue: "A form save automatically launches a long ruleset with no warning or visible status.", correct: "Use a deliberate action for longer rules, explain scope, save inputs first, show progress and result, and link to job evidence", options: ["Use a deliberate action for longer rules, explain scope, save inputs first, show progress and result, and link to job evidence", "Keep the automatic launch hidden", "Remove all rules from forms"] },
  { id: "FB-03", issue: "A hidden runtime prompt resolves to a member different from the visible form POV.", correct: "Use approved form members or display the prompt, show the resolved scope, and reject ambiguous context", options: ["Use approved form members or display the prompt, show the resolved scope, and reject ambiguous context", "Trust the last-used value", "Calculate every member"] },
  { id: "FB-04", issue: "Calculated gross margin and closing cash can be edited because the form shares their Account rows with input accounts.", correct: "Protect calculated and sourced cells while keeping only owned assumptions and controlled adjustments writable", options: ["Protect calculated and sourced cells while keeping only owned assumptions and controlled adjustments writable", "Allow overrides on every row", "Move calculations to cell comments"] },
] as const;

export const dashboardCases = [
  { id: "DB-01", issue: "The dashboard shows twelve colourful charts but no exception, target, trend, owner, or decision.", correct: "Keep only decision-relevant KPIs with definitions, comparisons, thresholds, exceptions, owners, and drill paths", options: ["Keep only decision-relevant KPIs with definitions, comparisons, thresholds, exceptions, owners, and drill paths", "Add more chart types", "Remove all labels"] },
  { id: "DB-02", issue: "Revenue is filtered to Pune while COGS and margin remain at company total.", correct: "Apply and display one consistent dimensional filter context across related KPIs or label deliberate differences", options: ["Apply and display one consistent dimensional filter context across related KPIs or label deliberate differences", "Let each tile keep its last filter", "Hide the Entity filter"] },
  { id: "DB-03", issue: "An executive KPI recalculates margin differently from the approved Phase 14 statement logic.", correct: "Source the dashboard from reconciled ApexPlan ASO results and reuse governed KPI definitions without independent logic", options: ["Source the dashboard from reconciled ApexPlan ASO results and reuse governed KPI definitions without independent logic", "Create a dashboard-only formula", "Use spreadsheet totals"] },
  { id: "DB-04", issue: "A red capacity exception cannot be traced to plant, product, period, cause, action, or owner.", correct: "Provide context-preserving drill or linked navigation to the governed exception and supporting form", options: ["Provide context-preserving drill or linked navigation to the governed exception and supporting form", "Show only the red colour", "Add the details to a separate email"] },
] as const;

export const smartViewCases = [
  { id: "SV-01", issue: "A user changes the Smart View POV and immediately submits without refreshing the sheet.", correct: "Refresh after the POV change, verify the displayed scope, edit only writable cells, submit, then refresh and reconcile", options: ["Refresh after the POV change, verify the displayed scope, edit only writable cells, submit, then refresh and reconcile", "Submit first and inspect later", "Copy the old values into the new POV"] },
  { id: "SV-02", issue: "A workbook contains formulas and copied values that replace governed Plan1 calculations.", correct: "Keep the connected Planning form or ad hoc grid authoritative and use workbook formulas only for transparent analysis outside governed stored outputs", options: ["Keep the connected Planning form or ad hoc grid authoritative and use workbook formulas only for transparent analysis outside governed stored outputs", "Upload every spreadsheet formula", "Disconnect the workbook before submission"] },
  { id: "SV-03", issue: "An ASO parent-level value is submitted from an ad hoc sheet.", correct: "Submit only to authorized writable level-zero intersections and confirm aggregation through the governed process", options: ["Submit only to authorized writable level-zero intersections and confirm aggregation through the governed process", "Submit to any visible parent", "Write directly to calculated totals"] },
  { id: "SV-04", issue: "A shared workbook stores a stale private POV, hidden rows, and no refresh or reconciliation instructions.", correct: "Publish a controlled template with visible POV, connection instructions, refresh-submit-refresh steps, version, owner, and control totals", options: ["Publish a controlled template with visible POV, connection instructions, refresh-submit-refresh steps, version, owner, and control totals", "Let each user repair the workbook", "Hide the connection details and POV"] },
] as const;

export const uxTestCases = [
  { id: "UX-01", issue: "A form opens quickly for the administrator but slowly for planners with realistic security and hierarchy scope.", correct: "Test first and repeated open, refresh, save, rule launch, and navigation with representative roles, data, hierarchies, and network conditions", options: ["Test first and repeated open, refresh, save, rule launch, and navigation with representative roles, data, hierarchies, and network conditions", "Use administrator timing only", "Increase the browser timeout"] },
  { id: "UX-02", issue: "Suppression makes the form faster but removes a required blank input row.", correct: "Fail the design because performance settings must preserve required input, Dynamic Calc behavior, context, and Smart View use", options: ["Fail the design because performance settings must preserve required input, Dynamic Calc behavior, context, and Smart View use", "Keep the faster form", "Ask users to type the missing row name"] },
  { id: "UX-03", issue: "A reviewer can open the form and edit Working data despite being assigned read-only responsibility.", correct: "Correct form and member security, retest the exact role, and retain negative write evidence", options: ["Correct form and member security, retest the exact role, and retain negative write evidence", "Tell the reviewer not to save", "Hide the Save button with training"] },
  { id: "UX-04", issue: "Keyboard users cannot identify focus, colour is the only exception indicator, and instructions are in a screenshot.", correct: "Provide keyboard-operable controls, visible focus, text or icon status, readable labels, sufficient contrast, and in-product instructions", options: ["Provide keyboard-operable controls, visible focus, text or icon status, readable labels, sufficient contrast, and in-product instructions", "Use brighter colours only", "Move all guidance into a PDF"] },
] as const;

export const uxExecutionSequence = [
  "Select the intended role and task, then open the approved navigation flow rather than browsing every application artifact",
  "Confirm application, cube, Scenario, Version, Year, Period, Entity, Product scope, currency, source status, and writable ownership",
  "Refresh the form or Smart View sheet before editing, especially after any POV, user-variable, suppression, or member-selection change",
  "Enter only owned assumptions in visibly writable cells; add required comments or supporting detail and resolve inline validation before save",
  "Save the input, deliberately launch the associated Phase 15 rule with the resolved context, and monitor the resulting job or message",
  "Review calculated values, exceptions, totals, status, and source-to-output trace; do not overwrite protected results to force agreement",
  "Use the dashboard or Smart View analysis to compare scenario, target, trend, capacity, margin, cash, and exception impact with one visible filter context",
  "Refresh, reconcile Plan1 and ApexPlan ASO controls, retain evidence, record exceptions and decisions, and complete the next workflow handoff",
] as const;

export const uxReconciliationControls = [
  "Visible POV, page selections, user variables, dashboard filters, Smart View POV, rule prompts, and job scope all represent the same approved planning slice",
  "Editable, protected, calculated, sourced, read-only, comment, attachment, Smart List, and supporting-detail behaviors match the form design contract",
  "Pune 820 plus Noida 560 equals 1,380 production starts, required hours equal 410 and 280, and all lot-size and capacity controls pass",
  "Revenue 559,579.64, COGS 356,855.544608, net income 88,293.071544, closing cash 383,448.796152, and balance control zero agree with approved rules",
  "Dashboard KPI totals and exceptions agree with ApexPlan ASO, preserve filter context, and drill to the correct governed detail without new calculation logic",
  "Web and Smart View unchanged refresh or rerun results are repeatable, security prevents unauthorized writes, and performance remains within approved thresholds",
] as const;

export const uxWalkthroughControls = [
  "The captures use only the authorized ApexPlan training environment and hide tenant URLs, user identities, notifications, and unrelated client data",
  "One Forecast, Working, FY25 training cycle and the same role-based tasks are used across navigation, forms, rules, jobs, dashboards, and Smart View",
  "Every screenshot includes enough context to identify the artifact, visible POV or filters, editable or protected behavior, trainee action, and expected validation evidence",
  "Smart View screenshots show connection, visible POV, refresh-submit-refresh behavior, writable scope, and reconciliation rather than an uncontrolled offline workbook",
  "Screenshots supplement the form catalogue, KPI definitions, test results, timings, job IDs, security evidence, exception log, reviewer, and approval",
] as const;

export const uxHomeworkMissions = [
  { id: "journey", title: "Map the role-based journey", output: "Task flow" },
  { id: "form", title: "Complete the production input form", output: "Validated submission" },
  { id: "dashboard", title: "Resolve dashboard design decisions", output: "KPI workspace" },
  { id: "smartview", title: "Control the Smart View workflow", output: "Workbook procedure" },
  { id: "readout", title: "Present the UX release decision", output: "UX handoff" },
] as const;

export const uxArtifacts = [
  "Approved role-to-task and navigation map covering planner, reviewer, operations, finance, administrator, and executive journeys, frequencies, decisions, handoffs, and owners",
  "Form catalogue and design specifications covering cube, purpose, roles, POV, rows, columns, pages, precision, suppression, protection, validation, rules, menus, instructions, and expected size",
  "Configured Plan1 input, review, exception, and control forms with consistent naming, folders, visible context, owned write scope, calculated outputs, and user guidance",
  "Rule-association and validation package showing save behavior, action menus, runtime-prompt resolution, progress, messages, job evidence, protected cells, and failure handling",
  "ApexPlan ASO dashboard catalogue with KPI definitions, filters, targets, comparisons, thresholds, drill paths, owners, refresh behavior, and reconciliation",
  "Controlled Smart View package with connections, templates, visible POV, ad hoc permissions, writable level-zero scope, refresh-submit-refresh procedure, rules, and controls",
  "Usability, accessibility, security, functional, negative, browser, Smart View, suppression, first-open, repeated-open, refresh, save, rule, dashboard, and performance test evidence",
  "Operating guide and Phase 17 handoff with artifact ownership, access requirements, support model, known limitations, exceptions, screenshots, reviewers, and approvals",
] as const;

export const uxKnowledgeQuestions = [
  { id: "UK-01", prompt: "Why should Plan1 input forms and ApexPlan ASO dashboards remain distinct?", correct: "Plan1 owns controlled input and detailed calculations while ApexPlan ASO presents reconciled aggregate management results", options: ["Plan1 owns controlled input and detailed calculations while ApexPlan ASO presents reconciled aggregate management results", "Both cubes should accept the same manual input", "Dashboards should calculate independent financial logic"] },
  { id: "UK-02", prompt: "What should a user do after changing the Smart View POV and before editing?", correct: "Refresh and verify the visible scope before changing writable cells", options: ["Refresh and verify the visible scope before changing writable cells", "Submit the old grid", "Hide the POV"] },
  { id: "UK-03", prompt: "When should Suppress Missing Blocks be retained?", correct: "Only after representative before-and-after testing proves better performance without losing required rows or correct behavior", options: ["Only after representative before-and-after testing proves better performance without losing required rows or correct behavior", "Always", "Only when the form has no data"] },
  { id: "UK-04", prompt: "What does a useful management dashboard add?", correct: "Governed decision context through consistent filters, comparisons, thresholds, exceptions, ownership, and drill paths—not new business logic", options: ["Governed decision context through consistent filters, comparisons, thresholds, exceptions, ownership, and drill paths—not new business logic", "As many chart types as possible", "Writable financial statement totals"] },
  { id: "UK-05", prompt: "What proves a form is ready for release?", correct: "The intended role can complete the task correctly and efficiently while access, rules, messages, calculations, controls, performance, and recovery all pass", options: ["The intended role can complete the task correctly and efficiently while access, rules, messages, calculations, controls, performance, and recovery all pass", "The administrator can open it", "The form contains every dimension"] },
] as const;

export const uxScreenshots = [
  { id: "UX-UI-01", title: "Open the role-based ApexPlan navigation flow", path: "Home → Navigation Flow → Planner or Reviewer cluster", asset: "01-role-based-navigation.png", capture: "Navigation cluster showing only the role's planning tasks, status or sequence cues, and links to forms, dashboards, and exceptions.", action: "Confirm the user role and trace the required task journey from input through review, calculation, reporting, and handoff.", evidence: "Role, navigation flow, cluster, artifact links, task sequence, owner, and reviewer captured." },
  { id: "UX-UI-02", title: "Review the form folder and catalogue", path: "Navigator → Application → Forms → ApexPlan training folders", asset: "02-form-folder-catalogue.png", capture: "Form folders and form names organized by Sales, Production, Inventory, Cost, Financial, Controls, and Review responsibilities.", action: "Match each form to its catalogue entry, cube, owner, target role, frequency, and approved rule association.", evidence: "Folder structure, form names, cubes, roles, owners, catalogue version, and approval captured." },
  { id: "UX-UI-03", title: "Enter and validate the production allocation", path: "Production Planning → Plant allocation form", asset: "03-production-input-form.png", capture: "Plan1 form showing Forecast, Working, FY25 context, Pune and Noida inputs, protected calculated hours, totals, lot-size status, comments, and action menu.", action: "Enter 820 Pune and 560 Noida starts, save, resolve validation, and prove 1,380 starts with 410 and 280 hours.", evidence: "POV, editable and protected cells, comments, saved inputs, validations, calculated values, total, user, and timestamp captured." },
  { id: "UX-UI-04", title: "Launch the associated business rule", path: "Production form → Actions or Rules → approved Phase 15 rule", asset: "04-form-rule-launch-and-result.png", capture: "Form action or Rules panel, runtime prompt drawer or resolved form context, launch confirmation, completion message, and refreshed calculated outputs.", action: "Confirm the resolved scope before launch, save inputs, execute the rule, inspect status, refresh, and trace to the job ID.", evidence: "Rule version, prompts, form context, user, job ID, status, message, duration, outputs, and rerun captured." },
  { id: "UX-UI-05", title: "Review the integrated financial control form", path: "Financial Planning → Integrated outlook and controls", asset: "05-financial-review-form.png", capture: "Read-only or protected Plan1 review form showing revenue, COGS, margin, net income, closing cash, balance control, source status, and exception links.", action: "Trace each result to Phase 14 logic and confirm the form exposes no unauthorized manual override of calculated totals.", evidence: "POV, sources, values, protection, balance control, rule job, reviewer, and exception status captured." },
  { id: "UX-UI-06", title: "Open the management decision dashboard", path: "Dashboards → Integrated planning outlook", asset: "06-management-dashboard.png", capture: "ApexPlan ASO dashboard showing volume, revenue, margin, inventory, capacity, net income, cash, and critical exception KPIs with visible filters.", action: "Apply the approved Scenario, Version, Year, Period, and Entity context and explain the decision supported by each retained KPI.", evidence: "Dashboard version, visible filters, KPI definitions, targets, variances, exception counts, refresh time, and reviewer captured." },
  { id: "UX-UI-07", title: "Drill from an exception to governed detail", path: "Management dashboard → capacity or margin exception → linked detail", asset: "07-dashboard-filter-and-drill.png", capture: "Selected dashboard exception with preserved filter context and destination form or analysis showing plant, product, period, cause, action, and owner.", action: "Drill from the KPI to the supporting exception and return without losing the approved dashboard context.", evidence: "Source KPI, filters, destination, supporting values, exception owner, action, return path, and reconciliation captured." },
  { id: "UX-UI-08", title: "Connect Smart View and open the governed form", path: "Excel → Smart View → Shared or Private Connections → Planning → ApexPlan → Forms", asset: "08-smart-view-connect-open-form.png", capture: "Smart View panel and connected ApexPlan form showing connection, form name, visible POV, writable cells, protected cells, and Planning ribbon.", action: "Open the approved form, change the POV only within scope, refresh, and verify that the sheet matches the web form before editing.", evidence: "Connection, user role, form, POV, refresh timestamp, web-to-sheet control totals, and writable scope captured." },
  { id: "UX-UI-09", title: "Submit and reconcile Smart View changes", path: "Smart View connected form → edit → Submit Data → Refresh", asset: "09-smart-view-submit-refresh.png", capture: "Edited level-zero cells, visible POV, submit result, refreshed values, rule launch if applicable, comments, and control totals.", action: "Submit only authorized inputs, refresh, run the approved rule when required, and prove web and Smart View values agree.", evidence: "Before and after values, submit result, user, POV, rule and job reference, refreshed totals, variance, and reviewer retained." },
  { id: "UX-UI-10", title: "Perform controlled ad hoc analysis", path: "Smart View → ApexPlan form or cube → Ad Hoc Analysis", asset: "10-smart-view-ad-hoc-analysis.png", capture: "Ad hoc sheet showing visible dimensions, member selections, aliases, suppression settings, zoom result, read-only reporting values, and reconciliation totals.", action: "Pivot and zoom only within the assigned role, keep the POV visible, avoid shadow calculations, and reconcile the final view to the dashboard or source form.", evidence: "Template version, connection, POV, row and column members, suppression, aliases, controls, refresh timestamp, and conclusion captured." },
] as const;
