import type { LessonDefinition } from "@/types/course";

export const goLiveLessons = [
  { id: "go-live-foundations", number: "01", title: "Go-Live foundations and entry controls", duration: "18 min", type: "concept" },
  { id: "go-live-access", number: "02", title: "Open production access safely", duration: "30 min", type: "wizard" },
  { id: "go-live-automation", number: "03", title: "Activate integrations and schedules", duration: "34 min", type: "simulation" },
  { id: "go-live-first-cycle", number: "04", title: "Execute the first live planning cycle", duration: "36 min", type: "simulation" },
  { id: "go-live-reconciliation", number: "05", title: "Reconcile production and reporting", duration: "34 min", type: "assessment" },
  { id: "go-live-incidents", number: "06", title: "Control incidents and rollback boundaries", duration: "28 min", type: "assessment" },
  { id: "go-live-hypercare", number: "07", title: "Transfer control to Hypercare", duration: "26 min", type: "wizard" },
  { id: "go-live-homework", number: "08", title: "Applied first-cycle lab", duration: "50 min", type: "assessment" },
  { id: "go-live-exit-gate", number: "09", title: "Production validation pack and exit gate", duration: "26 min", type: "exit-gate" },
] as const satisfies readonly LessonDefinition[];

export type GoLiveLessonId = (typeof goLiveLessons)[number]["id"];

export const goLiveEntryControls = [
  "Phase 24 provides a signed, time-stamped decision for an exact release and production state, including conditions, scope, recovery state, and activation authority",
  "The cutover runbook and decision record identify what may be enabled, what remains disabled, named owners, activation waves, checkpoints, and breach actions",
  "Production support, Hypercare, business owners, integration owners, security, service administration, and decision authority are present or on-call",
  "Monitoring, alerts, job logs, incident severity, escalation, communications, evidence repository, and rollback or containment procedures are active",
  "The first-cycle business calendar, source cutoff, user wave, forms, rules, approvals, schedules, reconciliations, reporting, and success criteria are approved",
] as const;

export const productionAccessCases = [
  { id: "ACC-01", issue: "The production home page is visible, but the application identity and environment cannot be distinguished from UAT.", correct: "Stop and verify production identity, approved URL, application name, release, and support banner before any business action", options: ["Stop and verify production identity, approved URL, application name, release, and support banner before any business action", "Assume the newest environment is production", "Enter a test value to find out", "Ask users to compare browser history"] },
  { id: "ACC-02", issue: "The administrator can open every card, but a Sales Planner has not completed representative positive and negative access checks.", correct: "Keep the user wave closed until the named planner proves authorized access and protected functions remain denied", options: ["Keep the user wave closed until the named planner proves authorized access and protected functions remain denied", "Use administrator testing as sufficient", "Grant the planner administrator temporarily", "Open access and test during the cycle"] },
  { id: "ACC-03", issue: "The signed decision authorizes named pilot users first, but all directory groups are enabled together.", correct: "Restore the approved access wave, validate pilot behavior and monitoring, then authorize the next wave at its checkpoint", options: ["Restore the approved access wave, validate pilot behavior and monitoring, then authorize the next wave at its checkpoint", "Continue because security testing passed", "Disable monitoring to reduce alerts", "Let group owners decide individually"] },
  { id: "ACC-04", issue: "A user reports a UAT Smart View connection in the approved production template.", correct: "Withdraw the template, correct the controlled production connection, retest refresh and submit, and redistribute the versioned file", options: ["Withdraw the template, correct the controlled production connection, retest refresh and submit, and redistribute the versioned file", "Ask each user to edit the connection", "Leave UAT available as fallback", "Remove Smart View from support scope"] },
] as const;

export const automationCases = [
  { id: "AUT-01", issue: "A scheduled actuals integration is enabled before the approved activation wave and overlaps the completed manual final load.", correct: "Disable the schedule, confirm no duplicate processing, reconcile the current state, and reactivate only at the runbook checkpoint", options: ["Disable the schedule, confirm no duplicate processing, reconcile the current state, and reactivate only at the runbook checkpoint", "Let both loads complete", "Delete one process result", "Change the source total"] },
  { id: "AUT-02", issue: "The production integration succeeds, but its file name, checksum, process ID, accepted count, and rejected count are not retained.", correct: "Keep the checkpoint incomplete until the source identity, process result, counts, totals, exceptions, and acceptance are recorded", options: ["Keep the checkpoint incomplete until the source identity, process result, counts, totals, exceptions, and acceptance are recorded", "Accept the green status", "Record only the screenshot", "Rerun without investigating"] },
  { id: "AUT-03", issue: "The first scheduled publish to ApexPlan ASO starts before Plan1 calculations and business approval finish.", correct: "Enforce the approved dependency, stop or contain the publish, validate target state, and rerun only after accepted Plan1 completion", options: ["Enforce the approved dependency, stop or contain the publish, validate target state, and rerun only after accepted Plan1 completion", "Let the publish finish and refresh later", "Approve ASO independently", "Disable Plan1 calculations"] },
  { id: "AUT-04", issue: "A service account authenticates, but monitoring and failure notification route to a former project member.", correct: "Correct the production support ownership and prove alert receipt before declaring the automation operational", options: ["Correct the production support ownership and prove alert receipt before declaring the automation operational", "Accept because authentication works", "Remove the alert", "Wait for the first failure"] },
] as const;

export const firstCycleCases = [
  { id: "CYC-01", issue: "A planner begins in the wrong Scenario and Version because the form opens with stale personal preferences.", correct: "Stop input, restore the approved production POV, confirm visible context, assess any saved data, and reinforce the controlled starting view", options: ["Stop input, restore the approved production POV, confirm visible context, assess any saved data, and reinforce the controlled starting view", "Continue and move the data later", "Hide the POV", "Reset every user without review"] },
  { id: "CYC-02", issue: "The first production calculation finishes faster than UAT but produces different totals.", correct: "Treat correctness as the primary control; hold downstream work and reconcile inputs, scope, rule version, dependencies, and outputs", options: ["Treat correctness as the primary control; hold downstream work and reconcile inputs, scope, rule version, dependencies, and outputs", "Approve because performance improved", "Change expected totals", "Publish to ASO and compare later"] },
  { id: "CYC-03", issue: "The rule job succeeds, but an unchanged scoped rerun doubles a movement account.", correct: "Open an incident, contain downstream publishing, diagnose repeatability, restore or correct safely, rerun, and reconcile", options: ["Open an incident, contain downstream publishing, diagnose repeatability, restore or correct safely, rerun, and reconcile", "Avoid rerunning in future", "Post a balancing adjustment", "Accept the first result"] },
  { id: "CYC-04", issue: "Planning Approvals show Submitted, but the Task Manager owner and due time remain unassigned.", correct: "Correct the operational ownership and schedule linkage before treating the workflow checkpoint as complete", options: ["Correct the operational ownership and schedule linkage before treating the workflow checkpoint as complete", "Treat Submitted as full approval", "Ask the project manager to approve everything", "Remove Task Manager from the cycle"] },
  { id: "CYC-05", issue: "A pilot user completes the cycle while an approved Go-Live condition remains open.", correct: "Retain the condition in the command center, execute its checkpoint, monitor the threshold, and apply its breach action or closure authority", options: ["Retain the condition in the command center, execute its checkpoint, monitor the threshold, and apply its breach action or closure authority", "Close it because the user succeeded", "Move it silently to a backlog", "Wait until Hypercare ends"] },
] as const;

export const productionReconciliationCases = [
  { id: "REC-01", issue: "Plan1 totals match the first-cycle form, but ApexPlan ASO is lower after publishing.", correct: "Hold reporting acceptance, reconcile publish POV and mapping, correct and rerun safely, then verify ASO, dashboard, and Smart View totals", options: ["Hold reporting acceptance, reconcile publish POV and mapping, correct and rerun safely, then verify ASO, dashboard, and Smart View totals", "Approve Plan1 only", "Refresh repeatedly", "Hide the dashboard"] },
  { id: "REC-02", issue: "Dashboard totals match ASO, but the displayed Scenario filter differs from the approved first-cycle POV.", correct: "Reject the visual result, restore the governed filter context, and reconcile the same POV across source, Plan1, ASO, dashboard, and Smart View", options: ["Reject the visual result, restore the governed filter context, and reconcile the same POV across source, Plan1, ASO, dashboard, and Smart View", "Accept because totals match", "Remove the filter label", "Ask users to remember the context"] },
  { id: "REC-03", issue: "Smart View refresh agrees with the web form, but an unauthorized cell allows submit.", correct: "Fail the security control, contain affected access, correct and retest positive and negative behavior, and assess submitted data", options: ["Fail the security control, contain affected access, correct and retest positive and negative behavior, and assess submitted data", "Accept the reconciliation", "Tell users not to submit", "Protect the worksheet locally"] },
  { id: "REC-04", issue: "Rounded dashboard values appear equal while full-precision control totals differ materially.", correct: "Use full-precision reconciliation and approved tolerance; presentation rounding cannot hide a material production variance", options: ["Use full-precision reconciliation and approved tolerance; presentation rounding cannot hide a material production variance", "Approve the visible dashboard", "Increase rounding", "Change the tolerance after review"] },
] as const;

export const goLiveIncidentCases = [
  { id: "INC-01", issue: "A Severity 1 data-integrity incident occurs before the rollback deadline.", correct: "Contain affected processing, invoke the named decision authority, evaluate the approved rollback trigger, preserve evidence, and communicate the controlled state", options: ["Contain affected processing, invoke the named decision authority, evaluate the approved rollback trigger, preserve evidence, and communicate the controlled state", "Let users continue while investigating", "Have the developer decide", "Wait until the deadline passes"] },
  { id: "INC-02", issue: "A single planner cannot access a noncritical dashboard; the supported report works and no protected access is exposed.", correct: "Log and triage the incident, use the tested workaround, monitor cumulative impact, and continue only within approved Go-Live conditions", options: ["Log and triage the incident, use the tested workaround, monitor cumulative impact, and continue only within approved Go-Live conditions", "Rollback automatically", "Ignore the user", "Grant administrator access"] },
  { id: "INC-03", issue: "Three medium incidents share one integration dependency and support queues are approaching capacity.", correct: "Assess the combined business and support exposure, escalate the trend, and reconsider containment or activation waves", options: ["Assess the combined business and support exposure, escalate the trend, and reconsider containment or activation waves", "Manage each incident independently", "Lower their severity", "Open the next user wave"] },
  { id: "INC-04", issue: "A fix is available during Go-Live but was built directly in production and has no controlled test evidence.", correct: "Reject the uncontrolled change; use emergency-change governance with impact analysis, approval, packaging, testing, deployment, rollback, and reconciliation", options: ["Reject the uncontrolled change; use emergency-change governance with impact analysis, approval, packaging, testing, deployment, rollback, and reconciliation", "Accept because it fixes the issue", "Document it after Hypercare", "Ask one user to test it"] },
] as const;

export const goLiveActivationSequence = [
  "Confirm the signed Phase 24 authorization, exact release, open conditions, recovery state, and activation scope",
  "Open production to support and the approved pilot-user wave; verify identity, positive access, and negative access",
  "Enable integrations, service accounts, schedules, alerts, and dependencies one approved wave at a time",
  "Execute the first controlled input, calculation, approval, and reporting cycle using the governed POV",
  "Reconcile source, Plan1, ApexPlan ASO, dashboards, and Smart View at full precision",
  "Assess incidents, condition checkpoints, performance, support capacity, and rollback or containment thresholds",
  "Authorize the next user or automation wave and issue the approved status communication",
  "Freeze the production validation pack and transfer open ownership, evidence, and monitoring to Hypercare",
] as const;

export const hypercareHandoffControls = [
  "The production release, enabled users, schedules, integrations, forms, rules, reports, Smart View templates, and known disabled scope are inventoried",
  "Every incident, condition, residual risk, workaround, severity, owner, SLA, target, evidence, and escalation route is transferred without losing history",
  "Monitoring covers access, jobs, integrations, calculations, performance, workflow, reconciliations, support volume, and business-calendar checkpoints",
  "Daily Hypercare cadence, attendees, command-center source, status format, change control, decision authority, and exit criteria are approved",
  "Business, support, operations, security, integration, service administration, and functional owners explicitly accept the handoff",
] as const;

export const goLiveScreenshots = [
  { id: "GL-UI-01", title: "Verify the production application identity", path: "Approved production URL → ApexPlan Home", asset: "01-production-home.png", capture: "ApexPlan production home showing the application identity and authorized navigation without exposing tenant URL, user identity, notifications, or unrelated data.", action: "Compare environment, application name, release reference, visible navigation, support notice, and approved activation scope before any production transaction.", evidence: "Production identity, application, release, timestamp, reviewer, and allowed starting actions are retained." },
  { id: "GL-UI-02", title: "Execute representative access smoke testing", path: "ApexPlan Home → role-based navigation", asset: "02-user-access-smoke-test.png", capture: "Representative planner navigation showing authorized cards or tasks and a documented protected function that remains unavailable.", action: "Test one named pilot role for login, authorized navigation, form access, rule launch, workflow, reporting, and a negative access path.", evidence: "User role, positive results, negative result, exceptions, timestamp, and security reviewer acceptance are recorded." },
  { id: "GL-UI-03", title: "Prove the first production integration", path: "Data Integration → Process Details", asset: "03-production-integration-job.png", capture: "Production Process Details showing integration, period or POV, process ID, status, accepted and rejected counts, timing, and drillable log context.", action: "Verify the approved source file and checksum, execute once at the runbook checkpoint, inspect rejects and warnings, and reconcile source to accepted plus rejected totals.", evidence: "File identity, checksum, process ID, runtime, counts, totals, exceptions, and acceptance owner are linked." },
  { id: "GL-UI-04", title: "Validate the production calculation job", path: "ApexPlan → Jobs or Rules → job details", asset: "04-calculation-job-status.png", capture: "Production calculation job details showing rule or ruleset, cube, runtime prompts or POV, status, start and finish, duration, and messages.", action: "Confirm the deployed rule version and bounded POV, execute in approved sequence, inspect messages, compare runtime, and prove an unchanged scoped rerun is repeatable.", evidence: "Rule version, prompts, job ID, duration, messages, repeatability result, and reviewer are retained." },
  { id: "GL-UI-05", title: "Execute the first-cycle production form", path: "ApexPlan → first-cycle planning form", asset: "05-first-cycle-form.png", capture: "Production form showing visible Scenario, Version, Year, Period, Entity and other relevant POV, writable inputs, protected calculations, validation, and action controls.", action: "Open as the authorized pilot planner, confirm the governed POV, enter the approved small test or live input, save, validate, calculate, and compare the expected result.", evidence: "User role, form, POV, input reference, validation, calculated result, job reference, and timestamp are captured." },
  { id: "GL-UI-06", title: "Confirm production workflow ownership", path: "Planning Approvals or Task Manager → first-cycle status", asset: "06-workflow-approval-status.png", capture: "Production approval or task view showing owner, status, due time, dependency, submission or approval state, and exceptions.", action: "Trace the pilot activity from planner through reviewer or approver, verify Task Manager ownership and due time, and resolve any unassigned or blocked step.", evidence: "Approval unit or task, owner, status, timestamps, dependency, exception, and acceptance are recorded." },
  { id: "GL-UI-07", title: "Reconcile Plan1 production controls", path: "ApexPlan → production reconciliation form", asset: "07-plan1-reconciliation.png", capture: "Control form comparing approved source, loaded Plan1 values, calculations, full-precision expected and actual totals, variance, tolerance, and status.", action: "Reconcile the first-cycle POV from source through load, calculation, movement, workflow, and control totals before reporting acceptance.", evidence: "Source and Plan1 totals, variance, tolerance, exceptions, rerun reference, reviewer, and sign-off are retained." },
  { id: "GL-UI-08", title: "Validate ApexPlan ASO reporting", path: "ApexPlan → management dashboard", asset: "08-aso-dashboard-validation.png", capture: "Production ApexPlan ASO dashboard showing visible filters and reconciled first-cycle volume, revenue, inventory, capacity, cost, margin, cash, or exception KPIs.", action: "Confirm the approved filter context, publish timestamp, KPI definitions, drill path, refresh time, and agreement with Plan1 control totals.", evidence: "Dashboard version, filters, KPI controls, Plan1-to-ASO variance, publish job, refresh time, and business reviewer are captured." },
  { id: "GL-UI-09", title: "Complete the production Smart View check", path: "Excel → Smart View → approved production connection", asset: "09-smart-view-production-check.png", capture: "Approved production Smart View template showing connection context, form or grid, visible POV, refresh result, writable and protected cells, and reconciliation controls.", action: "Open the versioned template as the authorized pilot role, confirm production connection and POV, refresh, perform only the approved submit test, and reconcile with web and reporting outputs.", evidence: "Template version, connection, role, POV, refresh and submit result, protected-cell behavior, totals, and timestamp are retained." },
] as const;

export const goLiveHomeworkMissions = [
  { id: "access", title: "Control the user wave", description: "Verify production identity, pilot access, negative security, and approved connection paths." },
  { id: "automation", title: "Activate automation", description: "Sequence integrations, schedules, dependencies, evidence, and alerts safely." },
  { id: "cycle", title: "Run the first cycle", description: "Control POV, calculation, repeatability, workflow, and open conditions." },
  { id: "incident", title: "Protect production", description: "Triage incidents without weakening rollback or emergency-change controls." },
  { id: "handoff", title: "Recommend Hypercare handoff", description: "Sequence activation evidence and write the production validation readout." },
] as const;

export const goLiveArtifacts = [
  "Signed Phase 24 decision, authorized release, activation scope, open conditions, recovery state, and first checkpoint",
  "Production identity, access-wave, positive and negative security, navigation, Smart View connection, and user communication evidence",
  "Integration, service-account, source-file, checksum, schedule, dependency, alert, process-result, reject, and rerun evidence",
  "First-cycle form, governed POV, inputs, validations, calculations, repeatability, workflow, approval, and Task Manager evidence",
  "Full-precision source-to-Plan1-to-ApexPlan-ASO-to-dashboard-to-Smart-View reconciliation and business acceptance",
  "Production incident, trend, containment, rollback-boundary, emergency-change, resolution, retest, communication, and decision log",
  "Performance, monitoring, support-volume, condition-checkpoint, user-wave, automation-wave, and status-communication evidence",
  "Accepted Hypercare handoff with inventory, owners, conditions, risks, incidents, monitoring, cadence, escalation, and exit criteria",
] as const;

export const goLiveKnowledgeQuestions = [
  { id: "K-01", question: "What does a successful login prove?", options: ["Only that authentication worked; role-based access, data security, functions, workflow, and negative paths still require evidence", "All security is correct", "The release is fully operational", "All users may be enabled"], correct: "Only that authentication worked; role-based access, data security, functions, workflow, and negative paths still require evidence" },
  { id: "K-02", question: "When is a production automation checkpoint complete?", options: ["When the approved dependency, source identity, execution, counts, totals, exceptions, alerts, evidence, and owner acceptance are complete", "When the job is green", "When the schedule is enabled", "When no user complains"], correct: "When the approved dependency, source identity, execution, counts, totals, exceptions, alerts, evidence, and owner acceptance are complete" },
  { id: "K-03", question: "What should happen when production calculation runtime improves but totals change?", options: ["Hold downstream work and reconcile correctness before considering performance", "Approve because it is faster", "Change expected totals", "Publish and investigate later"], correct: "Hold downstream work and reconcile correctness before considering performance" },
  { id: "K-04", question: "Can the team apply an untested direct production fix during Go-Live?", options: ["No; use the approved emergency-change path with impact, authority, packaging, test, deployment, rollback, and reconciliation", "Yes, for any Severity 1 issue", "Yes, when a developer is confident", "Yes, if documented later"], correct: "No; use the approved emergency-change path with impact, authority, packaging, test, deployment, rollback, and reconciliation" },
  { id: "K-05", question: "What does Phase 25 hand to Phase 26?", options: ["A known production state, completed first-cycle evidence, open conditions and incidents, monitoring, owners, support cadence, and accepted Hypercare controls", "Only a Go-Live announcement", "Only screenshots", "An empty incident queue"], correct: "A known production state, completed first-cycle evidence, open conditions and incidents, monitoring, owners, support cadence, and accepted Hypercare controls" },
] as const;
