export const performanceTestingLessons = [
  { id: "perf-foundations", number: "01", title: "Performance purpose, scope, and readiness", duration: "20 min", type: "concept" },
  { id: "perf-workload-nfr", number: "02", title: "Define workloads and measurable targets", duration: "32 min", type: "assessment" },
  { id: "perf-baseline", number: "03", title: "Create a controlled performance baseline", duration: "30 min", type: "wizard" },
  { id: "perf-single-user", number: "04", title: "Measure critical operations", duration: "34 min", type: "simulation" },
  { id: "perf-concurrency", number: "05", title: "Simulate concurrent planning usage", duration: "36 min", type: "assessment" },
  { id: "perf-diagnostics", number: "06", title: "Diagnose evidence and bottlenecks", duration: "34 min", type: "assessment" },
  { id: "perf-optimization", number: "07", title: "Optimize safely and prove improvement", duration: "34 min", type: "assessment" },
  { id: "perf-walkthrough", number: "08", title: "Execute the performance evidence walkthrough", duration: "32 min", type: "guided-screenshot" },
  { id: "perf-homework", number: "09", title: "Applied performance engineering lab", duration: "52 min", type: "assessment" },
  { id: "perf-exit-gate", number: "10", title: "Results, capacity, and exit decision", duration: "26 min", type: "exit-gate" },
] as const;

export type PerformanceTestingLessonId = (typeof performanceTestingLessons)[number]["id"];

export const performanceReadinessControls = [
  "Phase 19 functional SIT has passed and the same release candidate, metadata, rules, forms, integrations, security, workflow, and reporting artifacts are frozen for the baseline",
  "A dedicated non-production performance environment is approved, sized and configured comparably enough for the stated conclusions, with maintenance and background jobs controlled",
  "Representative data volume, user roles, user variables, POVs, form inputs, rule prompts, reports, integrations, and peak-period business journeys are versioned",
  "Service-level targets define the operation, population, percentile or statistic, concurrency, data volume, network assumptions, error tolerance, measurement window, and owner",
  "Monitoring, reset, cleanup, test-user handling, evidence retention, stop conditions, defect workflow, functional reconciliation, and decision authority are agreed before execution",
] as const;

export const performanceNfrCases = [
  { id: "NFR-01", issue: "The requirement says every screen must be fast.", correct: "Replace it with named operations, representative POV and volume, user count, percentile target, error rate, conditions, and business owner", options: ["Replace it with named operations, representative POV and volume, user count, percentile target, error rate, conditions, and business owner", "Use a universal two-second target", "Ask testers whether the application feels fast"] },
  { id: "NFR-02", issue: "Averages meet target, but a meaningful share of users experience long delays.", correct: "Evaluate the agreed percentile, maximum, errors, and distribution as well as the average", options: ["Evaluate the agreed percentile, maximum, errors, and distribution as well as the average", "Approve from the average alone", "Remove the slowest runs"] },
  { id: "NFR-03", issue: "The expected close-day peak is 50 concurrent planners, yet only one administrator is timed.", correct: "Retain single-user baselines and add a representative concurrent workload for 50 users with realistic roles, POVs, operations, and arrival lag", options: ["Retain single-user baselines and add a representative concurrent workload for 50 users with realistic roles, POVs, operations, and arrival lag", "Multiply the administrator time by 50", "Defer all load evidence to production"] },
  { id: "NFR-04", issue: "A test reaches 100 users but no business forecast supports that number.", correct: "Tie normal, peak, stress, and growth levels to user and transaction forecasts, operating windows, and approved capacity assumptions", options: ["Tie normal, peak, stress, and growth levels to user and transaction forecasts, operating windows, and approved capacity assumptions", "Keep 100 because it is a round number", "Call it capacity without documenting assumptions"] },
] as const;

export const performanceBaselineCases = [
  { id: "BL-01", issue: "The second run is much faster because caches and data state changed.", correct: "Classify cold and warm runs, execute approved warm-up, reset mutable data, keep run order, and compare equivalent samples", options: ["Classify cold and warm runs, execute approved warm-up, reset mutable data, keep run order, and compare equivalent samples", "Keep only the fastest run", "Mix both results without labels"] },
  { id: "BL-02", issue: "Results were captured while daily maintenance and another data load were running.", correct: "Invalidate or clearly isolate the run, control background activity, rerun in the approved window, and record unavoidable interference", options: ["Invalidate or clearly isolate the run, control background activity, rerun in the approved window, and record unavoidable interference", "Average the interference away", "Change the target after testing"] },
  { id: "BL-03", issue: "Test data has one month and 20 products, while production will contain years of history and the complete product hierarchy.", correct: "Build a representative volume model covering density, dimensionality, history, blocks or slices, and realistic query and calculation scope", options: ["Build a representative volume model covering density, dimensionality, history, blocks or slices, and realistic query and calculation scope", "Extrapolate linearly from the small dataset", "Test only the company total"] },
  { id: "BL-04", issue: "A rule improved from 42 to 25 seconds after a code change, but results were not compared.", correct: "Reconcile functional outputs and controls before accepting any performance improvement", options: ["Reconcile functional outputs and controls before accepting any performance improvement", "Approve because elapsed time improved", "Move correctness checks to UAT"] },
] as const;

export const performanceConcurrencyCases = [
  { id: "LOAD-01", issue: "The team plans to run simulateConcurrentUsage in production to obtain realistic results.", correct: "Use an authorized test environment because simulated operations can update data; baseline, reset, reconcile, and clean up there", options: ["Use an authorized test environment because simulated operations can update data; baseline, reset, reconcile, and clean up there", "Run in production outside business hours", "Use read-only tests in production without approval"] },
  { id: "LOAD-02", issue: "Fifty users all launch at exactly the same instant, although the business forecast describes a six-second arrival pattern.", correct: "Configure the approved user count, iterations, operations, POVs, and realistic lag, and retain the requirement input and report", options: ["Configure the approved user count, iterations, operations, POVs, and realistic lag, and retain the requirement input and report", "Use zero lag for every workload", "Reduce users until the test passes"] },
  { id: "LOAD-03", issue: "All simulated users are Service Administrators, but planners use different forms, variables, and access.", correct: "Use representative existing users where appropriate or document the simulation-role limitation and separately prove role-specific journeys", options: ["Use representative existing users where appropriate or document the simulation-role limitation and separately prove role-specific journeys", "Assume administrator results represent every user", "Disable security during the test"] },
  { id: "LOAD-04", issue: "A 20-minute peak test passes, so the team claims endurance and capacity are proven.", correct: "State only the evidence obtained; run separate peak, stress, recovery, endurance, and growth tests where required", options: ["State only the evidence obtained; run separate peak, stress, recovery, endurance, and growth tests where required", "Treat peak as proof of every workload", "Rename the test endurance"] },
] as const;

export const performanceDiagnosticCases = [
  { id: "DG-01", issue: "A business rule is slow, so the tester immediately rewrites it.", correct: "Correlate the exact timestamp and POV with Activity Report, Jobs, rule logs, commands, data scope, and repeatable baseline before changing design", options: ["Correlate the exact timestamp and POV with Activity Report, Jobs, rule logs, commands, data scope, and repeatable baseline before changing design", "Rewrite the whole rule from memory", "Add more parallel rules"] },
  { id: "DG-02", issue: "A form opens slowly only for one POV with many descendants and unsuppressed rows.", correct: "Compare equivalent runs and inspect form layout, suppression, member selections, dynamic calculations, attached rules, security, and data density", options: ["Compare equivalent runs and inspect form layout, suppression, member selections, dynamic calculations, attached rules, security, and data density", "Blame the browser immediately", "Remove the form from scope"] },
  { id: "DG-03", issue: "The Activity Report identifies a long request, but the test log has no exact start time or operation ID.", correct: "Treat correlation as incomplete, improve timestamp and identifier capture, rerun, and link client, job, and environment evidence", options: ["Treat correlation as incomplete, improve timestamp and identifier capture, rerun, and link client, job, and environment evidence", "Assume the longest request is the test", "Use a screenshot without timestamps"] },
  { id: "DG-04", issue: "Application Diagnostics reports a design concern that is unrelated to the measured bottleneck.", correct: "Record and prioritize it by verified impact; do not claim it caused the issue without controlled evidence", options: ["Record and prioritize it by verified impact; do not claim it caused the issue without controlled evidence", "Apply every recommendation immediately", "Ignore all diagnostics findings"] },
] as const;

export const performanceOptimizationCases = [
  { id: "OPT-01", issue: "A large calculation processes the full cube after a planner changes three cells.", correct: "Assess a bounded FIX or grid-aware Groovy approach, prove security and correctness, then compare the same workload before and after", options: ["Assess a bounded FIX or grid-aware Groovy approach, prove security and correctness, then compare the same workload before and after", "Remove calculation controls", "Convert every rule to Groovy automatically"] },
  { id: "OPT-02", issue: "A dashboard is slow because every tile queries broad dynamic hierarchies and unused periods.", correct: "Reduce unnecessary query scope, review aggregation and suppression design, preserve the required decision view, and retest identical POVs", options: ["Reduce unnecessary query scope, review aggregation and suppression design, preserve the required decision view, and retest identical POVs", "Delete the slowest KPI", "Cache a static screenshot"] },
  { id: "OPT-03", issue: "Parallel jobs shorten one batch but create contention and failures during peak use.", correct: "Optimize the complete schedule and dependency chain, govern concurrency, and measure throughput, errors, user impact, and recovery", options: ["Optimize the complete schedule and dependency chain, govern concurrency, and measure throughput, errors, user impact, and recovery", "Maximize parallel jobs", "Measure only the fastest job"] },
  { id: "OPT-04", issue: "The optimized build meets targets once but regresses during the repeat run.", correct: "Do not approve; investigate variability, rerun the controlled sample, reconcile outputs, and require stable target compliance", options: ["Do not approve; investigate variability, rerun the controlled sample, reconcile outputs, and require stable target compliance", "Approve the first passing run", "Increase the target"] },
] as const;

export const performanceWorkloadCases = [
  { id: "PW-01", issue: "Open Sales Input form at representative Product × Market × Month POV for 50 users.", correct: "Measure cold and warm single-user baselines, then minimum, average, percentile, maximum, errors, and throughput under approved arrival lag", options: ["Measure cold and warm single-user baselines, then minimum, average, percentile, maximum, errors, and throughput under approved arrival lag", "Record one stopwatch value", "Use the empty default POV"] },
  { id: "PW-02", issue: "Save the planning form and run its attached validation and calculation rules.", correct: "Control the changed cells and starting state, capture save plus rule behavior, reconcile values, and reset before equivalent iterations", options: ["Control the changed cells and starting state, capture save plus rule behavior, reconcile values, and reset before equivalent iterations", "Change random values each time", "Skip output reconciliation"] },
  { id: "PW-03", issue: "Run the end-to-end ruleset and publish Plan1 results to ApexPlan ASO.", correct: "Measure every job and the complete chain, capture queue and execution time, and verify the same final controls and ASO reconciliation", options: ["Measure every job and the complete chain, capture queue and execution time, and verify the same final controls and ASO reconciliation", "Measure only the final publish", "Ignore queued duration"] },
  { id: "PW-04", issue: "Open management dashboard, Smart View grid, report, and book during the peak workload.", correct: "Use approved representative artifacts and POVs, measure response and errors by channel, and keep business outputs consistent", options: ["Use approved representative artifacts and POVs, measure response and errors by channel, and keep business outputs consistent", "Test the smallest artifact only", "Use screenshots from SIT as timing proof"] },
] as const;

export const performanceExecutionSequence = [
  "Approve workload model, targets, capacity assumptions, test types, environment comparability, roles, data volume, tools, schedule, stop conditions, and exit criteria",
  "Freeze the release candidate and performance pack; reset data, control background activity, record service and application configuration, and perform approved warm-up",
  "Run repeated single-user cold and warm baselines for critical forms, saves, rules, integrations, data maps, Smart View grids, dashboards, reports, and batch chains",
  "Prepare and review simulateConcurrentUsage inputs, users or test modes, operations, POVs, iterations, arrival lag, reset and cleanup, then execute only in the test environment",
  "Run normal, peak, stress, recovery, and endurance workloads that are actually in scope; capture response, throughput, errors, resource indicators, jobs, and timestamps",
  "Correlate outliers with Activity Report, Jobs, Process Details, Calculation Manager logs, Application Diagnostics, design, data shape, network assumptions, and competing work",
  "Prioritize one evidence-backed bottleneck, change one controlled design area, deploy a versioned build, rerun the identical workload, reconcile results, and quantify improvement",
  "Summarize target compliance, variance and stability, capacity headroom, defects, residual risks, limitations, operational monitoring, rollback, owners, and the authorized exit decision",
] as const;

export const performanceControlChecks = [
  "Each result traces to workload ID, build, environment, timestamp and time zone, role, artifact, POV, data volume, user count, iteration, lag, and evidence files",
  "Minimum, average, agreed percentile, maximum, throughput, success count, error rate, queue time where relevant, and sample size are reported without deleting inconvenient runs",
  "Cold, warm, normal, peak, stress, recovery, and endurance results are labelled accurately; no test claims more than its duration, workload, and observations prove",
  "Every optimization has before-and-after evidence from equivalent conditions plus functional, security, workflow, financial, and Plan1-to-ApexPlan ASO reconciliation",
  "Test users, credentials, files, changed data, generated artifacts, background jobs, and environment state are safely controlled and cleaned after execution",
  "Unmet targets, intermittent results, defects, constraints, environment differences, capacity limits, workarounds, monitoring thresholds, owners, and acceptance decisions remain visible",
] as const;

export const performanceWalkthroughControls = [
  "Show the approved test environment, release build, representative data-volume profile, workload ID, target, time zone, user count, iterations, and arrival-lag assumptions",
  "Correlate each tested operation to exact Jobs, Process Details, Activity Report, rule-log, simulation-report, diagnostic, or reporting evidence using timestamps and identifiers",
  "Capture an unchanged baseline, the diagnosed bottleneck, the versioned optimization, the equivalent retest, the calculated improvement, and reconciled functional outputs",
  "Include normal and peak results plus only the additional stress, recovery, or endurance evidence actually executed; state exclusions and limitations clearly",
  "Hide tenant URLs, usernames, email addresses, passwords, tokens, connections, notification recipients, and unrelated client data in screenshots and downloadable files",
] as const;

export const performanceHomeworkMissions = [
  { id: "targets", label: "Workloads and targets", purpose: "Turn business peaks into measurable, traceable test conditions." },
  { id: "baseline", label: "Controlled baseline", purpose: "Measure critical ApexPlan operations under repeatable conditions." },
  { id: "load", label: "Concurrent workload", purpose: "Design safe self-service load and capacity evidence." },
  { id: "diagnose", label: "Diagnose and optimize", purpose: "Connect observations to one controlled improvement." },
  { id: "readout", label: "Performance decision", purpose: "Defend target compliance, headroom, risks, and exit." },
] as const;

export const performanceArtifacts = [
  "Approved performance strategy covering scope, exclusions, workload model, test types, environment, tools, roles, schedule, risk, stop, reset, cleanup, and exit criteria",
  "Measurable NFR and workload catalogue with business journey, artifact, role, POV, data volume, user forecast, concurrency, lag, target statistic, threshold, error rate, and owner",
  "Controlled baseline pack with release and configuration versions, data profile, cold and warm runs, samples, raw timestamps, Jobs, Process Details, and functional controls",
  "Concurrent-usage input package and execution evidence with approved operations, users or test mode, iterations, lag, reports, errors, cleanup, and non-production authorization",
  "Diagnostic package linking slow requests to Activity Report, Jobs, rule logs, Process Details, Application Diagnostics, design analysis, root cause, and defect records",
  "Before-and-after optimization report with equivalent workload, versioned change, response distribution, throughput, errors, stability, calculated improvement, and reconciled outputs",
  "Capacity and operational-readiness assessment with normal and peak headroom, stress or endurance evidence where applicable, monitoring, thresholds, run windows, recovery, rollback, and owners",
  "Approved performance exit record with target status, exceptions, unresolved defects, limitations, workarounds, residual risks, waivers, UAT conditions, and decision authority",
] as const;

export const performanceKnowledgeQuestions = [
  { id: "K-01", prompt: "What makes a performance target testable?", correct: "A named operation, representative conditions, workload and volume, statistic, threshold, error tolerance, and owner", options: ["A named operation, representative conditions, workload and volume, statistic, threshold, error tolerance, and owner", "A statement that the page should be fast", "One administrator's opinion"] },
  { id: "K-02", prompt: "Where should simulateConcurrentUsage be executed?", correct: "In an authorized test environment with controlled data because supported operations may change data", options: ["In an authorized test environment with controlled data because supported operations may change data", "In production for realism", "Against any tenant without cleanup"] },
  { id: "K-03", prompt: "Why are average times alone insufficient?", correct: "They can hide slow percentiles, maxima, errors, variability, queueing, and poor user experience", options: ["They can hide slow percentiles, maxima, errors, variability, queueing, and poor user experience", "Oracle does not report averages", "Only minimum time matters"] },
  { id: "K-04", prompt: "When is an optimization proven?", correct: "Equivalent before-and-after workloads improve stably while functional, security, and reconciliation results remain correct", options: ["Equivalent before-and-after workloads improve stably while functional, security, and reconciliation results remain correct", "The code is shorter", "One retest is faster"] },
  { id: "K-05", prompt: "What is required for the Phase 20 exit?", correct: "Traceable target results, controlled defects and exceptions, capacity conclusions, reconciled outputs, residual-risk approval, and a formal decision", options: ["Traceable target results, controlled defects and exceptions, capacity conclusions, reconciled outputs, residual-risk approval, and a formal decision", "Every result must be under two seconds", "No Activity Report findings"] },
] as const;

export const performanceScreenshots = [
  { id: "PERF-UI-01", title: "Confirm the performance baseline", path: "Performance control sheet + Oracle environment and application references", asset: "01-performance-environment-baseline.png", capture: "Approved test environment, build, application configuration, representative data profile, workload version, time zone, maintenance window, and background-job state.", action: "Match the deployed release and test pack to the approved baseline before warm-up or timed runs.", evidence: "Environment, build IDs, data-volume counts, configuration, test window, owners, reset result, and reviewer retained." },
  { id: "PERF-UI-02", title: "Review the Activity Report", path: "Tools → Activity Reports", asset: "02-activity-report-overview.png", capture: "Report period and the sections showing user experience, longest requests, forms, rules, calculations, or other material performance indicators.", action: "Align the report window with the recorded test timestamps and identify evidence-backed candidates for investigation.", evidence: "Report date, time zone, request or artifact, duration, frequency, users, timestamp correlation, and exported report reference." },
  { id: "PERF-UI-03", title: "Inspect slow business rules", path: "Activity Report → long-running rules / Calculation Manager → launch and log messages", asset: "03-business-rule-performance.png", capture: "Named ApexPlan rule, matching job and POV, elapsed time, and Calculation Manager log sections that isolate expensive steps.", action: "Correlate the identical rule and prompts, identify the slow command or data scope, and record a testable optimization hypothesis.", evidence: "Rule and build version, prompts, job ID, log timestamps, commands, baseline duration, root-cause evidence, and defect link." },
  { id: "PERF-UI-04", title: "Measure forms and dashboards", path: "Planning forms and ApexPlan ASO dashboards + Activity Report form/request sections", asset: "04-form-dashboard-performance.png", capture: "Representative Sales Input form and management dashboard at the approved POV with load, save, refresh, or query timings.", action: "Run the defined cold and warm samples without changing scope, then compare target statistic, errors, and returned business values.", evidence: "Artifact, POV, rows and columns, suppression, attached rules, role, samples, timings, errors, and reconciliation retained." },
  { id: "PERF-UI-05", title: "Measure integrations and publish jobs", path: "Data Integration → Process Details + Application → Jobs", asset: "05-integration-publish-performance.png", capture: "Actuals integration and Plan1-to-ApexPlan ASO movement showing process or job IDs, queue, start, end, status, row counts, and target controls.", action: "Separate queue and execution duration, correlate competing work, and confirm row and financial controls after each run.", evidence: "Process and job IDs, modes, counts, queue and execution times, errors, rerun, source and target totals, and reviewer." },
  { id: "PERF-UI-06", title: "Configure concurrent usage", path: "EPM Automate working folder + Inbox/Outbox", asset: "06-concurrent-usage-input.png", capture: "Redacted requirement.csv and supporting ZIP inventory with operation types, artifact names, users, inputs, iterations, lag, and test name.", action: "Peer-review every operation and file, confirm test-environment authorization, upload the package, and retain its controlled version.", evidence: "Package version, checksum or identifier, operations, users or test mode, iterations, lag, upload evidence, reset, and approval." },
  { id: "PERF-UI-07", title: "Review concurrent-usage results", path: "EPM Automate output + Inbox/Outbox report and error files", asset: "07-concurrent-usage-results.png", capture: "Simulation summary showing operations, samples or iterations, user load, minimum, maximum, average, errors, and generated files.", action: "Compare each result with its target and raw evidence; retain failures and outliers rather than editing them out.", evidence: "Command and test name, start and end, report file, error file, user load, results, target status, cleanup, and reviewer." },
  { id: "PERF-UI-08", title: "Run Application Diagnostics", path: "Oracle Planning diagnostics job or EPM Automate runApplicationDiagnostics → Inbox/Outbox", asset: "08-application-diagnostics.png", capture: "Completed diagnostics job and redacted report findings relevant to metadata, forms, or executed rules.", action: "Assess findings against measured bottlenecks, record impact and disposition, and avoid treating an unverified recommendation as root cause.", evidence: "Job or command, generated file, finding ID, affected artifact, recommendation, verified impact, owner, and disposition." },
  { id: "PERF-UI-09", title: "Compare optimization results", path: "Performance comparison sheet + matching Oracle jobs, reports, and controls", asset: "09-before-after-comparison.png", capture: "Equivalent before-and-after workload with release IDs, response statistics, throughput, errors, variability, improvement percentage, and functional controls.", action: "Confirm only the intended change differs, calculate improvement consistently, repeat the sample, and reconcile business outputs.", evidence: "Baseline and optimized builds, samples, min/average/percentile/max, errors, improvement, control variances, and approvers." },
  { id: "PERF-UI-10", title: "Review capacity and exit evidence", path: "Performance results dashboard / defect register / exit record", asset: "10-performance-exit-decision.png", capture: "Target compliance, normal and peak headroom, defects, stability, stress or endurance status, exceptions, limitations, risks, waivers, and decision.", action: "Reconcile summary metrics to raw runs, challenge every unmet target, and obtain the authorized Phase 20 exit decision.", evidence: "Workload totals, target status, defects, capacity conclusion, constraints, monitoring, risks, owners, waivers, decision, and date." },
] as const;
