"use client";

import { ArrowRight, BookOpenCheck, BriefcaseBusiness, Calculator, Camera, Check, CheckCircle2, ClipboardCheck, Download, Factory, Gauge, Info, Landmark, PlayCircle, ShieldCheck, TriangleAlert, Users } from "lucide-react";
import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react";
import {
  assetCapacityCases,
  capexFinancialCases,
  dependencyArtifacts,
  dependencyBuildSequence,
  dependencyExceptionCases,
  dependencyFormCases,
  dependencyHomeworkMissions,
  dependencyKnowledgeQuestions,
  dependencyReadinessControls,
  dependencyReconciliationControls,
  dependencyScreenshots,
  operationalHandoffCases,
  workforceActionCases,
  workforceCapexLessons,
  workforceCases,
  type WorkforceCapexLessonId,
} from "@/content/workforce-capex-dependencies-module";
import { manufacturingCostLessons } from "@/content/manufacturing-cost-cogs-module";
import { readTrackProgress, writeTrackProgress } from "@/lib/learning-progress";
import design from "./application-dimension-design-module.module.css";
import base from "./discovery-module.module.css";
import sales from "./sales-planning-build-module.module.css";
import styles from "./workforce-capex-dependencies-module.module.css";
import { LearningModuleFrame, type ModuleFeedback } from "./learning-module-frame";
import { OracleScreenshot } from "./oracle-screenshot";

type Answers = Record<string, string>;
type HomeworkId = (typeof dependencyHomeworkMissions)[number]["id"];
type WorkforceInputs = { requiredHours: number; paidHours: number; availabilityPct: number; currentFte: number; overtimeRate: number; monthlyFteCost: number };
type CapexInputs = { requiredHours: number; existingCapacity: number; overtimeHours: number; productivityHours: number; assetCapacity: number; assetCost: number; usefulLife: number; residualValue: number; leadTimeMonths: number; needInMonths: number };

const packPath = "/training/oracle-planning/phase-13/";
const defaultWorkforce: WorkforceInputs = { requiredHours: 410, paidHours: 160, availabilityPct: 85, currentFte: 3, overtimeRate: 350, monthlyFteCost: 45000 };
const defaultCapex: CapexInputs = { requiredHours: 560, existingCapacity: 450, overtimeHours: 30, productivityHours: 20, assetCapacity: 160, assetCost: 1200000, usefulLife: 60, residualValue: 0, leadTimeMonths: 2, needInMonths: 3 };

export function WorkforceCapexDependenciesModule() {
  const [activeLesson, setActiveLesson] = useState<WorkforceCapexLessonId>("dependency-foundations");
  const [completedLessons, setCompletedLessons] = useState<string[]>([]);
  const [feedback, setFeedback] = useState<ModuleFeedback>(null);
  const [readiness, setReadiness] = useState<string[]>([]);
  const [handoffAnswers, setHandoffAnswers] = useState<Answers>({});
  const [workforceAnswers, setWorkforceAnswers] = useState<Answers>({});
  const [actionAnswers, setActionAnswers] = useState<Answers>({});
  const [assetAnswers, setAssetAnswers] = useState<Answers>({});
  const [financialAnswers, setFinancialAnswers] = useState<Answers>({});
  const [exceptionAnswers, setExceptionAnswers] = useState<Answers>({});
  const [formAnswers, setFormAnswers] = useState<Answers>({});
  const [workforceInputs, setWorkforceInputs] = useState<WorkforceInputs>(defaultWorkforce);
  const [capexInputs, setCapexInputs] = useState<CapexInputs>(defaultCapex);
  const [ranWorkforce, setRanWorkforce] = useState(false);
  const [ranCapex, setRanCapex] = useState(false);
  const [reconciled, setReconciled] = useState<string[]>([]);
  const [sequence, setSequence] = useState<string[]>([]);
  const [activeHomework, setActiveHomework] = useState<HomeworkId>("workforce");
  const [readout, setReadout] = useState("");
  const [artifacts, setArtifacts] = useState<string[]>([]);
  const [summary, setSummary] = useState("");
  const [knowledgeAnswers, setKnowledgeAnswers] = useState<Answers>({});

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const stored = readTrackProgress("implementation");
      setCompletedLessons(stored.completedLessons);
      const saved = workforceCapexLessons.find((lesson) => lesson.id === stored.activeLesson);
      if (saved) setActiveLesson(saved.id);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  const workforceResult = useMemo(() => calculateWorkforce(workforceInputs), [workforceInputs]);
  const capexResult = useMemo(() => calculateCapex(capexInputs), [capexInputs]);
  const prerequisiteComplete = manufacturingCostLessons.every((lesson) => completedLessons.includes(lesson.id));
  const allCorrect = (items: readonly { id: string; correct: string }[], answers: Answers) => items.every((item) => answers[item.id] === item.correct);
  const knowledgeReady = dependencyKnowledgeQuestions.every((item) => knowledgeAnswers[item.id] === item.correct);
  const homeworkStatus: Record<HomeworkId, boolean> = {
    workforce: ranWorkforce && workforceResult.valid && near(workforceResult.productiveHoursPerFte, 136) && near(workforceResult.gapHours, 2),
    actions: allCorrect(workforceActionCases, actionAnswers),
    capex: ranCapex && capexResult.valid && capexResult.requiredAssets === 1 && near(capexResult.residualGap, 60) && near(capexResult.monthlyDepreciation, 20000),
    exceptions: allCorrect(dependencyExceptionCases, exceptionAnswers),
    readout: readout.trim().length >= 240,
  };
  const preview = useMemo(() => artifacts.length === dependencyArtifacts.length && summary.trim().length >= 220
    ? `${summary.trim()} Approved workforce actions and timely CapEx dependencies are now available for financial-statement integration; changed production or timing must trigger scoped operational, cost, and financial reruns.`
    : "Complete all eight dependency artifacts and provide a readiness summary of at least 220 characters.", [artifacts, summary]);

  function persist(nextCompleted: string[], lesson: WorkforceCapexLessonId) { writeTrackProgress("implementation", { completedLessons: nextCompleted, activeLesson: lesson, activeModuleId: "implementation-workforce-capex-dependencies", lastVisited: new Date().toISOString() }); }
  function goToLesson(id: WorkforceCapexLessonId) { setActiveLesson(id); setFeedback(null); persist(completedLessons, id); }
  function markComplete(message: string) { const next = completedLessons.includes(activeLesson) ? completedLessons : [...completedLessons, activeLesson]; setCompletedLessons(next); persist(next, activeLesson); setFeedback({ tone: "success", message }); }
  function toggle(setter: Dispatch<SetStateAction<string[]>>, item: string) { setter((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item]); }

  function validateLesson() {
    if (activeLesson === "dependency-foundations") {
      if (readiness.length !== dependencyReadinessControls.length) return setFeedback({ tone: "error", message: "Confirm all five dependency-planning readiness controls." });
      return markComplete("Operational hours, cost inputs, workforce drivers, asset assumptions, and custom-application boundaries are controlled.");
    }
    if (activeLesson === "operational-handoff") {
      if (!allCorrect(operationalHandoffCases, handoffAnswers)) return setFeedback({ tone: "error", message: "Resolve all Entity, change-control, hour-definition, and capability decisions." });
      return markComplete("The production-to-dependency handoff is versioned, locally feasible, precisely defined, and traceable.");
    }
    if (activeLesson === "workforce-requirement") {
      if (!allCorrect(workforceCases, workforceAnswers) || !ranWorkforce || !workforceResult.valid || !near(workforceResult.gapHours, 2)) return setFeedback({ tone: "error", message: "Run the Pune practice calculation and resolve productivity, rounding, local-gap, and skill cases." });
      return markComplete("Pune productive hours, exact and roster FTE, current capacity, and the two-hour gap reconcile.");
    }
    if (activeLesson === "workforce-actions") {
      if (!allCorrect(workforceActionCases, actionAnswers)) return setFeedback({ tone: "error", message: "Resolve all overtime, contractor, hiring-timing, and training decisions." });
      return markComplete("Workforce actions are compared by hours, timing, eligibility, cost, constraint, risk, and sustainability.");
    }
    if (activeLesson === "asset-capacity") {
      if (!allCorrect(assetCapacityCases, assetAnswers) || !ranCapex || !capexResult.valid || capexResult.requiredAssets !== 1 || !near(capexResult.residualGap, 60)) return setFeedback({ tone: "error", message: "Run the future capacity case and resolve mitigation, residual-gap, timing, and enabling-dependency decisions." });
      return markComplete("Operational mitigations reduce the asset gap to 60 hours and one timely asset creates 100 hours of headroom.");
    }
    if (activeLesson === "capex-financials") {
      if (!allCorrect(capexFinancialCases, financialAnswers) || !ranCapex || !capexResult.valid || !near(capexResult.monthlyDepreciation, 20000)) return setFeedback({ tone: "error", message: "Run the CapEx calculation and resolve depreciation, cash timing, capitalization, and business-case decisions." });
      return markComplete("Investment, timing, capitalization, cash, asset life, residual value, and depreciation are separated and governed.");
    }
    if (activeLesson === "dependency-exceptions") {
      if (!allCorrect(dependencyExceptionCases, exceptionAnswers)) return setFeedback({ tone: "error", message: "Resolve all overtime-limit, financial-tradeoff, rebalance-rerun, and aggregate-cube exceptions." });
      return markComplete("Dependency exceptions show operational and financial trade-offs, owners, reruns, decisions, and residual risk.");
    }
    if (activeLesson === "dependency-walkthrough") {
      if (!allCorrect(dependencyFormCases, formAnswers)) return setFeedback({ tone: "error", message: "Correct all summarized-grain, form-protection, scoped-execution, and traceability decisions." });
      return markComplete("The functional dependency forms and screenshot-guided execution runbook are ready for tenant evidence.");
    }
    if (activeLesson === "dependency-homework") {
      if (!Object.values(homeworkStatus).every(Boolean) || reconciled.length !== dependencyReconciliationControls.length || sequence.length !== dependencyBuildSequence.length) return setFeedback({ tone: "error", message: "Complete all five lab missions, six reconciliations, and the eight-step execution order." });
      return markComplete("Applied dependency lab complete. Workforce, CapEx, timing, finance, scenarios, and evidence are ready for review.");
    }
    if (artifacts.length !== dependencyArtifacts.length || summary.trim().length < 220 || !knowledgeReady) return setFeedback({ tone: "error", message: "Select all eight deliverables, provide a 220-character summary, and answer all five knowledge checks correctly." });
    markComplete("Phase 13 exit gate passed. Approved workforce and CapEx dependencies are ready for financial-statement integration.");
  }

  return <LearningModuleFrame activeLessonId={activeLesson} completedLessons={completedLessons} description="Translate approved production requirements into workforce capacity, controlled staffing actions, asset-capacity decisions, CapEx timing, cash flow, depreciation, and reconciled downstream dependencies." exitGate="Approve the workforce and CapEx dependency baseline, scenario decision, financial impacts, rerun evidence, and downstream handoff" exitGateIcon={<BriefcaseBusiness size={18} />} feedback={feedback} lessons={workforceCapexLessons} onSelectLesson={(id) => goToLesson(id as WorkforceCapexLessonId)} onValidate={validateLesson} phase={13} prerequisite={{ complete: prerequisiteComplete, message: "Complete Phase 12 so dependency decisions use approved production hours, labor and overhead costs, inventory, COGS, and margin impacts.", href: "/learn/manufacturing-cost-cogs", linkLabel: "Open Phase 12" }} stage="Build · Workforce and CapEx dependencies" title="Workforce & CapEx Dependencies" validateLabel={activeLesson === "dependency-handoff" ? "Approve dependency package" : undefined}>
    {activeLesson === "dependency-foundations" && <Foundations selected={readiness} onToggle={(item) => toggle(setReadiness, item)} />}
    {activeLesson === "operational-handoff" && <OperationalHandoff answers={handoffAnswers} onAnswer={(id, value) => setHandoffAnswers((current) => ({ ...current, [id]: value }))} />}
    {activeLesson === "workforce-requirement" && <WorkforceRequirement answers={workforceAnswers} onAnswer={(id, value) => setWorkforceAnswers((current) => ({ ...current, [id]: value }))} inputs={workforceInputs} onInput={setWorkforceInputs} result={workforceResult} ran={ranWorkforce} onRun={() => setRanWorkforce(true)} />}
    {activeLesson === "workforce-actions" && <WorkforceActions answers={actionAnswers} onAnswer={(id, value) => setActionAnswers((current) => ({ ...current, [id]: value }))} />}
    {activeLesson === "asset-capacity" && <AssetCapacity answers={assetAnswers} onAnswer={(id, value) => setAssetAnswers((current) => ({ ...current, [id]: value }))} inputs={capexInputs} onInput={setCapexInputs} result={capexResult} ran={ranCapex} onRun={() => setRanCapex(true)} />}
    {activeLesson === "capex-financials" && <CapexFinancials answers={financialAnswers} onAnswer={(id, value) => setFinancialAnswers((current) => ({ ...current, [id]: value }))} inputs={capexInputs} onInput={setCapexInputs} result={capexResult} ran={ranCapex} onRun={() => setRanCapex(true)} />}
    {activeLesson === "dependency-exceptions" && <DependencyExceptions answers={exceptionAnswers} onAnswer={(id, value) => setExceptionAnswers((current) => ({ ...current, [id]: value }))} />}
    {activeLesson === "dependency-walkthrough" && <FunctionalWalkthrough answers={formAnswers} onAnswer={(id, value) => setFormAnswers((current) => ({ ...current, [id]: value }))} />}
    {activeLesson === "dependency-homework" && <DependencyHomework active={activeHomework} onActive={setActiveHomework} status={homeworkStatus} workforce={<WorkforceCalculator inputs={workforceInputs} onInput={setWorkforceInputs} result={workforceResult} ran={ranWorkforce} onRun={() => setRanWorkforce(true)} />} actionAnswers={actionAnswers} onAction={(id, value) => setActionAnswers((current) => ({ ...current, [id]: value }))} capex={<CapexCalculator inputs={capexInputs} onInput={setCapexInputs} result={capexResult} ran={ranCapex} onRun={() => setRanCapex(true)} mode="capacity" />} exceptionAnswers={exceptionAnswers} onException={(id, value) => setExceptionAnswers((current) => ({ ...current, [id]: value }))} reconciled={reconciled} onReconcile={(item) => toggle(setReconciled, item)} sequence={sequence} onSequence={(item) => toggle(setSequence, item)} readout={readout} onReadout={setReadout} />}
    {activeLesson === "dependency-handoff" && <DependencyExitGate selected={artifacts} onToggle={(item) => toggle(setArtifacts, item)} summary={summary} onSummary={setSummary} answers={knowledgeAnswers} onAnswer={(id, value) => setKnowledgeAnswers((current) => ({ ...current, [id]: value }))} preview={preview} />}
  </LearningModuleFrame>;
}

function Foundations({ selected, onToggle }: { selected: string[]; onToggle: (item: string) => void }) { return <><Lead icon={<ShieldCheck size={23} />} eyebrow="Business outcome" title="Prove that the operating plan has timely people and assets, then expose the cost, cash, depreciation, margin, and execution trade-offs of closing each gap." /><p className={base.bodyCopy}>This phase does not build employee-level Workforce or asset-register-level Capital modules. It uses summarized, controlled drivers in the custom ApexPlan application to identify dependencies, compare actions, and hand approved impacts to financial planning.</p><div className={design.designSequence}>{["Production", "Hours", "FTE", "Actions", "Assets", "CapEx", "Finance"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong>{index < 6 && <ArrowRight size={13} />}</div>)}</div><h3 className={sales.sectionTitle}>Confirm the dependency boundary</h3><SelectionGrid items={dependencyReadinessControls} selected={selected} onToggle={onToggle} /><div className={sales.boundary}><div><strong>Phase 13 owns</strong><span>Summarized workforce capacity, action alternatives, asset capacity, CapEx business case, cash and depreciation impacts, scenarios, exceptions, and reconciliation.</span></div><div><strong>Phase 13 does not create</strong><span>Named employees, positions, requisitions, individual assets, procurement transactions, or dimensions that were not approved in the application design.</span></div></div></>; }

function OperationalHandoff({ answers, onAnswer }: AnswerProps) {
  const downloads = [["phase-13-workforce-capex-dependencies-practice-pack.zip", "Complete practice pack"], ["README.md", "Instructions"], ["production-dependency-handoff.csv", "Production handoff"], ["workforce-driver-baseline.csv", "Workforce drivers"], ["capex-scenario-baseline.csv", "CapEx scenario"], ["expected-dependency-results.csv", "Expected results"], ["dependency-test-cases.csv", "Test cases"], ["dependency-runbook.csv", "Runbook"], ["dependency-exception-log.csv", "Exception log"], ["dependency-reconciliation-template.csv", "Reconciliation"]] as const;
  return <><Lead icon={<Factory size={23} />} eyebrow="Controlled operating input" title="Carry approved plant requirements into dependency planning without losing Entity, Product capability, period, version, hour definition, or exception context." /><p className={base.bodyCopy}>Pune requires 410 hours for 820 Mixer Grinder starts; Noida requires 280 hours for 560 starts. Workforce and equipment decisions must use these governed local requirements rather than an unconstrained company total.</p><div className={sales.downloadGrid}>{downloads.map(([file, label]) => <a download href={`${packPath}${file}`} key={file}><Download size={17} /><div><strong>{label}</strong><small>{file}</small></div></a>)}</div><div className={styles.plantGrid}><Metric label="Pune" value="820 ÷ 2 = 410 h" detail="Primary plant requirement" /><Metric label="Noida" value="560 ÷ 2 = 280 h" detail="Approved alternate plant" /><Metric label="Company" value="1,380 starts / 690 h" detail="Reconciles to Phase 10" /></div><DecisionTable items={operationalHandoffCases} answers={answers} onAnswer={onAnswer} label="operational-handoff response" /></>;
}

function WorkforceRequirement(props: WorkforceCalculatorProps & AnswerProps) { return <><Lead icon={<Users size={23} />} eyebrow="Hours to workforce capacity" title="Calculate exact FTE for analysis, roster FTE for staffing, current productive capacity, local gap hours, and the financial scale of available responses." /><div className={sales.formula}>Productive hours per FTE = paid hours × productive availability<br />Exact required FTE = required hours ÷ productive hours per FTE<br /><strong>Gap hours = max(0, required hours − current FTE productive capacity)</strong></div><WorkforceCalculator {...props} /><DecisionTable items={workforceCases} answers={props.answers} onAnswer={props.onAnswer} label="workforce-requirement response" /></>; }

function WorkforceActions({ answers, onAnswer }: AnswerProps) { return <><Lead icon={<BriefcaseBusiness size={23} />} eyebrow="Match action to gap duration" title="Compare overtime, transfer, contractor, training, hiring, and production rebalance using timing, eligibility, constraints, cost, and residual risk." /><div className={styles.optionGrid}>{[["Overtime", "2 h × 350", "700", "Fast; limit and fatigue controlled"], ["Permanent hire", "1 roster FTE", "45,000 / month", "Lead time; recurring capacity"], ["Noida support", "Spare 128 h", "Needs feasibility", "Skill, travel, labor rules"], ["Production rebalance", "Plant plan change", "Rerun required", "Cost, inventory, logistics"]].map(([title, basis, value, note]) => <article key={title}><span>{title}</span><strong>{basis}</strong><b>{value}</b><small>{note}</small></article>)}</div><DecisionTable items={workforceActionCases} answers={answers} onAnswer={onAnswer} label="workforce-action response" /><div className={sales.controlNote}>The practice recommendation is controlled overtime for the isolated two-hour Pune gap—not an automatic permanent hire. A recurring or growing gap must be reevaluated with cumulative cost, workforce risk, and lead time.</div></>; }

function AssetCapacity(props: CapexCalculatorProps & AnswerProps) { return <><Lead icon={<Gauge size={23} />} eyebrow="Operations before investment" title="Reduce the gross asset gap with approved feasible mitigations, then size only the residual capacity need and verify that new capacity is timely." /><div className={sales.formula}>Residual capacity gap = max(0, required hours − existing capacity − overtime − productivity recovery)<br />Required assets = round up(residual gap ÷ capacity per asset)<br /><strong>Post-action headroom = existing + mitigations + timely new capacity − required hours</strong></div><CapexCalculator {...props} mode="capacity" /><DecisionTable items={assetCapacityCases} answers={props.answers} onAnswer={props.onAnswer} label="asset-capacity response" /></>; }

function CapexFinancials(props: CapexCalculatorProps & AnswerProps) { return <><Lead icon={<Landmark size={23} />} eyebrow="Investment to financial impact" title="Keep approval, purchase cash, capitalization, in-service timing, depreciation, operating cost, and margin impact as connected but distinct schedules." /><CapexCalculator {...props} mode="financial" /><DecisionTable items={capexFinancialCases} answers={props.answers} onAnswer={props.onAnswer} label="capex-financial response" /><div className={base.infoCallout}><Info size={19} /><div><strong>Capacity does not begin at approval</strong><p>The operational plan may use new capacity only after the asset and all enabling dependencies are ready for their intended use. Cash payments and depreciation follow different approved timelines.</p></div></div></>; }

function DependencyExceptions({ answers, onAnswer }: AnswerProps) { return <><Lead icon={<TriangleAlert size={23} />} eyebrow="Connected scenario decisions" title="Resolve workforce, capacity, timing, cash, depreciation, margin, and reporting exceptions together rather than optimizing one result in isolation." /><div className={styles.exceptionSummary}><TriangleAlert size={22} /><div><small>Decision principle</small><strong>CapEx is not the first response to a capacity gap—and it cannot solve a requirement before it is usable</strong><span>Preserve the base case, compare feasible mitigations, quantify financial and service impacts, and retain one approved scenario plus explicitly owned residual risks.</span></div></div><DecisionTable items={dependencyExceptionCases} answers={answers} onAnswer={onAnswer} label="dependency-exception response" /></>; }

function FunctionalWalkthrough({ answers, onAnswer }: AnswerProps) { return <><Lead icon={<Camera size={23} />} eyebrow="Tenant execution runbook" title="Use summarized functional forms to prove workforce and CapEx dependencies without pretending the custom application contains detailed Workforce or Capital modules." /><p className={base.bodyCopy}>Protect production requirements and calculated results, expose only owned dependency inputs, use Entity and Account rows at the approved month grain, validate rule prompts, and keep every action connected to its originating operational requirement and downstream financial impact.</p><DecisionTable items={dependencyFormCases} answers={answers} onAnswer={onAnswer} label="dependency-form response" /><ScreenshotWalkthrough /><div className={sales.scopeTag}>Screenshot slots are intentionally empty. Add one consistent ApexPlan training cycle after the Phase 13 forms, rules, scenarios, data movement, and reconciliations exist.</div></>; }

function DependencyHomework({ active, onActive, status, workforce, actionAnswers, onAction, capex, exceptionAnswers, onException, reconciled, onReconcile, sequence, onSequence, readout, onReadout }: { active: HomeworkId; onActive: (id: HomeworkId) => void; status: Record<HomeworkId, boolean>; workforce: React.ReactNode; actionAnswers: Answers; onAction: (id: string, value: string) => void; capex: React.ReactNode; exceptionAnswers: Answers; onException: (id: string, value: string) => void; reconciled: string[]; onReconcile: (item: string) => void; sequence: string[]; onSequence: (item: string) => void; readout: string; onReadout: (value: string) => void }) {
  const mission = dependencyHomeworkMissions.find((item) => item.id === active)!; const completed = Object.values(status).filter(Boolean).length;
  return <><Lead icon={<BookOpenCheck size={23} />} eyebrow="Applied hands-on lab" title="Complete the Pune workforce dependency and a future asset-capacity scenario, then present one controlled management recommendation." /><div className={base.homeworkMissionGrid}>{dependencyHomeworkMissions.map((item, index) => <button className={`${active === item.id ? base.homeworkMissionActive : ""} ${status[item.id] ? base.homeworkMissionDone : ""}`} key={item.id} onClick={() => onActive(item.id)} type="button"><span>{status[item.id] ? <CheckCircle2 size={17} /> : String(index + 1).padStart(2, "0")}</span><div><strong>{item.title}</strong><small>{item.output}</small></div></button>)}</div><div className={base.homeworkProgress}><div><span style={{ width: `${completed / dependencyHomeworkMissions.length * 100}%` }} /></div><strong>{completed} of {dependencyHomeworkMissions.length} missions complete</strong></div><section className={base.homeworkWorkspace}><header><div><small>Active mission</small><strong>{mission.title}</strong></div><span>{mission.output}</span></header>{active === "workforce" && workforce}{active === "actions" && <DecisionTable items={workforceActionCases} answers={actionAnswers} onAnswer={onAction} label="workforce-action response" />}{active === "capex" && capex}{active === "exceptions" && <DecisionTable items={dependencyExceptionCases} answers={exceptionAnswers} onAnswer={onException} label="dependency-exception response" />}{active === "readout" && <><h3 className={sales.sectionTitle}>Reconcile the connected dependency plan</h3><SelectionGrid items={dependencyReconciliationControls} selected={reconciled} onToggle={onReconcile} /><h3 className={sales.sectionTitle}>Confirm execution order</h3><div className={sales.sequence}>{dependencyBuildSequence.map((item) => <button className={sequence.includes(item) ? sales.confirmed : ""} key={item} onClick={() => onSequence(item)} type="button"><strong>{item}</strong><span>{sequence.includes(item) ? <Check size={15} /> : "Confirm"}</span></button>)}</div><label className={sales.summaryField}>Workforce and CapEx dependency recommendation<textarea rows={12} value={readout} onChange={(event) => onReadout(event.target.value)} placeholder="Summarize production scope and hours, workforce drivers, exact and roster FTE, gap and selected action, recurring-gap criteria, asset-capacity bridge, mitigations, required asset and timing, cash and depreciation, enabling dependencies, scenarios, exceptions, reruns, reconciliations, evidence, open items, owners, reviewer, and recommendation." /><small>{readout.trim().length}/240 minimum characters</small></label></>}</section></>;
}

function DependencyExitGate({ selected, onToggle, summary, onSummary, answers, onAnswer, preview }: { selected: string[]; onToggle: (item: string) => void; summary: string; onSummary: (value: string) => void; answers: Answers; onAnswer: (id: string, value: string) => void; preview: string }) { return <><Lead icon={<ClipboardCheck size={23} />} eyebrow="Phase deliverable" title="Hand off approved, timely, financially visible workforce and CapEx dependencies—not unconstrained headcount or asset wishes." /><h3 className={sales.sectionTitle}>Deliverable checklist</h3><SelectionGrid items={dependencyArtifacts} selected={selected} onToggle={onToggle} /><label className={sales.summaryField}>Dependency-planning readiness summary<textarea rows={12} value={summary} onChange={(event) => onSummary(event.target.value)} placeholder="Summarize operational handoff, summarized application grain, workforce drivers and calculation, action alternatives and decision, asset capacity and mitigations, CapEx sizing and enabling dependencies, cash and depreciation, scenario and exceptions, forms and access, job and rerun evidence, reconciliations, reporting and financial handoff, open items, owners, reviewer, and approval." /><small>{summary.trim().length}/220 minimum characters</small></label><h3 className={sales.sectionTitle}>Knowledge check</h3><div className={base.quizList}>{dependencyKnowledgeQuestions.map((question, index) => <fieldset key={question.id}><legend><span>{index + 1}</span>{question.prompt}</legend>{question.options.map((option) => <label key={option}><input checked={answers[question.id] === option} name={question.id} onChange={() => onAnswer(question.id, option)} type="radio" />{option}</label>)}</fieldset>)}</div><div className={sales.preview}><small>Generated Phase 13 handoff</small><p>{preview}</p><div>Approved operating plan <ArrowRight size={13} /> Feasible people and assets <ArrowRight size={13} /> Financial statement integration</div></div></>; }

function WorkforceCalculator({ inputs, onInput, result, ran, onRun }: WorkforceCalculatorProps) { return <CalculatorShell title="Workforce dependency engine" badge={result.valid ? result.gapHours > 0 ? `${format(result.gapHours, 2)} h gap` : "Capacity sufficient" : "Correct workforce inputs"} onRun={onRun}><div className={sales.inputGrid}><NumberField label="Required productive hours" value={inputs.requiredHours} step="0.01" onChange={(value) => onInput({ ...inputs, requiredHours: value })} /><NumberField label="Paid hours / FTE" value={inputs.paidHours} step="0.01" onChange={(value) => onInput({ ...inputs, paidHours: value })} /><NumberField label="Productive availability · %" value={inputs.availabilityPct} step="0.1" onChange={(value) => onInput({ ...inputs, availabilityPct: value })} /><NumberField label="Current FTE" value={inputs.currentFte} step="0.01" onChange={(value) => onInput({ ...inputs, currentFte: value })} /><NumberField label="Overtime rate · currency/hour" value={inputs.overtimeRate} step="0.01" onChange={(value) => onInput({ ...inputs, overtimeRate: value })} /><NumberField label="Monthly cost / FTE" value={inputs.monthlyFteCost} step="0.01" onChange={(value) => onInput({ ...inputs, monthlyFteCost: value })} /></div>{ran && <><div className={sales.resultStrip}><Result label="Productive hours / FTE" value={format(result.productiveHoursPerFte, 2)} /><Result label="Exact required FTE" value={format(result.exactFte, 3)} /><Result label="Roster FTE" value={format(result.rosterFte, 0)} primary /><Result label="Current capacity" value={`${format(result.currentCapacity, 2)} h`} /><Result label="Gap hours" value={format(result.gapHours, 2)} /><Result label="Roster gap" value={`${format(result.rosterGap, 0)} FTE`} /></div><div className={styles.actionCost}><Metric label="Short-term overtime" value={money(result.overtimeCost)} detail={`${format(result.gapHours, 2)} gap hours`} /><Metric label="Permanent monthly hire" value={money(result.hireMonthlyCost)} detail={`${format(result.rosterGap, 0)} roster FTE`} /></div></>}</CalculatorShell>; }

function CapexCalculator({ inputs, onInput, result, ran, onRun, mode }: CapexCalculatorProps) { return <CalculatorShell title={mode === "capacity" ? "Asset-capacity and CapEx engine" : "CapEx financial-impact engine"} badge={!result.valid ? "Correct CapEx inputs" : result.timely ? "Capacity timely" : "Asset arrives late"} onRun={onRun}><div className={sales.inputGrid}><NumberField label="Required machine hours" value={inputs.requiredHours} onChange={(value) => onInput({ ...inputs, requiredHours: value })} /><NumberField label="Existing capacity · hours" value={inputs.existingCapacity} onChange={(value) => onInput({ ...inputs, existingCapacity: value })} /><NumberField label="Approved overtime · hours" value={inputs.overtimeHours} onChange={(value) => onInput({ ...inputs, overtimeHours: value })} /><NumberField label="Productivity recovery · hours" value={inputs.productivityHours} onChange={(value) => onInput({ ...inputs, productivityHours: value })} /><NumberField label="Capacity / new asset" value={inputs.assetCapacity} onChange={(value) => onInput({ ...inputs, assetCapacity: value })} /><NumberField label="Cost / new asset" value={inputs.assetCost} onChange={(value) => onInput({ ...inputs, assetCost: value })} /><NumberField label="Useful life · months" value={inputs.usefulLife} onChange={(value) => onInput({ ...inputs, usefulLife: value })} /><NumberField label="Residual value / asset" value={inputs.residualValue} onChange={(value) => onInput({ ...inputs, residualValue: value })} /><NumberField label="Lead time · months" value={inputs.leadTimeMonths} onChange={(value) => onInput({ ...inputs, leadTimeMonths: value })} /><NumberField label="Capacity needed in · months" value={inputs.needInMonths} onChange={(value) => onInput({ ...inputs, needInMonths: value })} /></div>{ran && mode === "capacity" && <div className={sales.resultStrip}><Result label="Gross capacity gap" value={`${format(result.grossGap, 0)} h`} /><Result label="Approved mitigations" value={`${format(result.mitigations, 0)} h`} /><Result label="Residual gap" value={`${format(result.residualGap, 0)} h`} /><Result label="Required assets" value={format(result.requiredAssets, 0)} primary /><Result label="Post-action capacity" value={`${format(result.postCapacity, 0)} h`} /><Result label="Headroom" value={`${format(result.headroom, 0)} h`} /></div>}{ran && mode === "financial" && <div className={styles.financialGrid}><Metric label="Capital investment" value={money(result.investment)} detail={`${result.requiredAssets} asset × ${money(inputs.assetCost)}`} /><Metric label="Monthly depreciation" value={money(result.monthlyDepreciation)} detail={`${inputs.usefulLife}-month life`} /><Metric label="Lead-time result" value={result.timely ? "Timely" : "Late"} detail={`${inputs.leadTimeMonths} lead / ${inputs.needInMonths} needed`} /><Metric label="Post-action headroom" value={`${format(result.headroom, 0)} h`} detail="After timely capacity" /></div>}</CalculatorShell>; }

function CalculatorShell({ title, badge, onRun, children }: { title: string; badge: string; onRun: () => void; children: React.ReactNode }) { return <section className={sales.calculator}><header><div><Calculator size={18} /><strong>{title}</strong></div><span>{badge}</span></header>{children}<div className={sales.calculatorFooter}><p>Change inputs to test the control, then run the scoped calculation again.</p><button onClick={onRun} type="button"><PlayCircle size={15} />Run calculation</button></div></section>; }
function NumberField({ label, value, onChange, step = "1" }: { label: string; value: number; onChange: (value: number) => void; step?: string }) { return <label>{label}<input type="number" step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function Result({ label, value, primary = false }: { label: string; value: string; primary?: boolean }) { return <article className={primary ? sales.primaryResult : ""}><small>{label}</small><strong>{value}</strong></article>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><small>{label}</small><strong>{value}</strong><span>{detail}</span></article>; }
function Lead({ icon, eyebrow, title }: { icon: React.ReactNode; eyebrow: string; title: string }) { return <div className={base.lessonLead}>{icon}<div><small>{eyebrow}</small><strong>{title}</strong></div></div>; }
function SelectionGrid({ items, selected, onToggle }: { items: readonly string[]; selected: string[]; onToggle: (item: string) => void }) { return <div className={design.selectionGrid}>{items.map((item) => <button className={selected.includes(item) ? design.selectedCard : ""} key={item} onClick={() => onToggle(item)} type="button">{selected.includes(item) ? <CheckCircle2 size={17} /> : <span />}<strong>{item}</strong></button>)}</div>; }
function DecisionTable({ items, answers, onAnswer, label }: { items: readonly { id: string; issue: string; correct: string; options: readonly string[] }[]; answers: Answers; onAnswer: (id: string, value: string) => void; label: string }) { return <div className={design.mappingTable}>{items.map((item) => <div className={design.tableRow} key={item.id}><div><strong>{item.id}</strong><small>{item.issue}</small></div><select aria-label={`${item.id} ${label}`} value={answers[item.id] ?? ""} onChange={(event) => onAnswer(item.id, event.target.value)}><option value="">Select controlled response</option>{item.options.map((option) => <option key={option}>{option}</option>)}</select></div>)}</div>; }
function ScreenshotWalkthrough() { return <section className={sales.walkthrough}><div className={sales.walkthroughHeader}><div><Camera size={20} /><div><small>Screenshot-guided procedure</small><strong>Functional workforce and CapEx dependency walkthrough</strong></div></div><span>{dependencyScreenshots.length} guided steps</span></div><div className={sales.walkthroughGrid}>{dependencyScreenshots.map((step, index) => <article key={step.id}><div className={sales.stepTitle}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{step.id}</small><strong>{step.title}</strong></div></div><OracleScreenshot asset={step.asset} capture={step.capture} className={sales.screenshot} phase="phase-13" title={step.title} /><dl><div><dt>Navigation</dt><dd>{step.path}</dd></div><div><dt>Trainee action</dt><dd>{step.action}</dd></div><div><dt>Validation evidence</dt><dd>{step.evidence}</dd></div></dl></article>)}</div></section>; } 

function calculateWorkforce(input: WorkforceInputs) { const valid = input.requiredHours >= 0 && input.paidHours > 0 && input.availabilityPct > 0 && input.availabilityPct <= 100 && input.currentFte >= 0 && input.overtimeRate >= 0 && input.monthlyFteCost >= 0; const productiveHoursPerFte = valid ? input.paidHours * input.availabilityPct / 100 : 0; const exactFte = productiveHoursPerFte ? input.requiredHours / productiveHoursPerFte : 0; const rosterFte = Math.ceil(exactFte - 1e-9); const currentCapacity = input.currentFte * productiveHoursPerFte; const gapHours = Math.max(0, input.requiredHours - currentCapacity); const rosterGap = Math.max(0, rosterFte - Math.floor(input.currentFte)); return { valid, productiveHoursPerFte, exactFte, rosterFte, currentCapacity, gapHours, rosterGap, overtimeCost: gapHours * input.overtimeRate, hireMonthlyCost: rosterGap * input.monthlyFteCost }; }
function calculateCapex(input: CapexInputs) { const valid = input.requiredHours >= 0 && input.existingCapacity >= 0 && input.overtimeHours >= 0 && input.productivityHours >= 0 && input.assetCapacity > 0 && input.assetCost >= 0 && input.usefulLife > 0 && input.residualValue >= 0 && input.residualValue <= input.assetCost && input.leadTimeMonths >= 0 && input.needInMonths >= 0; const grossGap = Math.max(0, input.requiredHours - input.existingCapacity); const mitigations = input.overtimeHours + input.productivityHours; const residualGap = Math.max(0, grossGap - mitigations); const requiredAssets = valid ? Math.ceil((residualGap - 1e-9) / input.assetCapacity) : 0; const timely = input.leadTimeMonths <= input.needInMonths; const newCapacity = timely ? requiredAssets * input.assetCapacity : 0; const postCapacity = input.existingCapacity + mitigations + newCapacity; const investment = requiredAssets * input.assetCost; const monthlyDepreciation = valid ? requiredAssets * (input.assetCost - input.residualValue) / input.usefulLife : 0; return { valid, grossGap, mitigations, residualGap, requiredAssets, timely, postCapacity, headroom: postCapacity - input.requiredHours, investment, monthlyDepreciation }; }
function near(actual: number, expected: number) { return Math.abs(actual - expected) < 0.01; }
function format(value: number, digits = 2) { return value.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits }); }
function money(value: number) { return format(value, 2); }

type AnswerProps = { answers: Answers; onAnswer: (id: string, value: string) => void };
type WorkforceCalculatorProps = { inputs: WorkforceInputs; onInput: (value: WorkforceInputs) => void; result: ReturnType<typeof calculateWorkforce>; ran: boolean; onRun: () => void };
type CapexCalculatorProps = { inputs: CapexInputs; onInput: (value: CapexInputs) => void; result: ReturnType<typeof calculateCapex>; ran: boolean; onRun: () => void; mode?: "capacity" | "financial" };
